#!/bin/sh

#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2009 Sun Microsystems Inc. All Rights Reserved
#
# The contents of this file are subject to the terms
# of the Common Development and Distribution License
# (the License). You may not use this file except in
# compliance with the License.
#
# You can obtain a copy of the License at
# https://opensso.dev.java.net/public/CDDLv1.0.html or
# opensso/legal/CDDLv1.0.txt
# See the License for the specific language governing
# permission and limitations under the License.
#
# When distributing Covered Code, include this CDDL
# Header Notice in each file and include the License file
# at opensso/legal/CDDLv1.0.txt.
# If applicable, add the following below the CDDL Header,
# with the fields enclosed by brackets [] replaced by
# your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
#
# $Id: wssagentadmin,v 1.1 2009/06/12 22:19:28 huacui Exp $
#
#

if [ -z "$AGENT_HOME" ]; then
    AGENT_HOME=`dirname $0`/..
fi

if [ -z "$JAVA_HOME" ]; then
    JAVA_VM=java
else
    JAVA_VM=${JAVA_HOME}/bin/java
fi

OS_TYPE=`uname -s | tr '[a-z]' '[A-Z]'`

if [ "$OS_TYPE" = "AIX" ]; then
    AGENT_OPTS="-DamKeyGenDescriptor.provider=IBMJCE -DamCryptoDescriptor.provider=IBMJCE -DamRandomGenProvider=IBMJCE"
else

    AGENT_OPTS=
fi

AGENT_CLASSPATH=${AGENT_HOME}/lib/opensso-installtools-launcher.jar:${AGENT_HOME}/config

$JAVA_VM -classpath "$AGENT_CLASSPATH"  $AGENT_OPTS com.sun.identity.install.tools.launch.AdminToolLauncher $*
