//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-b27-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.11 at 10:33:54 AM PDT 
//


package com.sun.identity.liberty.ws.common.jaxb.ac;


/**
 * Refers to those characteristics that describe the processes and mechanisms
 * the Authentication Authority uses to initially create an association between a Principal
 * and the identity (or name) by which the Principal will be known
 * 
 * Java content class for Identification element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/allan/A-SVN/trunk/opensso/products/federation/library/xsd/liberty/lib-arch-authentication-context.xsd line 60)
 * <p>
 * <pre>
 * &lt;element name="Identification" type="{urn:liberty:ac:2003-08}IdentificationType"/>
 * </pre>
 * 
 */
public interface IdentificationElement
    extends javax.xml.bind.Element, com.sun.identity.liberty.ws.common.jaxb.ac.IdentificationType
{


}
