/**
 * UserManager.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.aspace.ftress.interfaces.soap;

public interface UserManager extends java.rmi.Remote {
    public com.aspace.ftress.interfaces.ftress.DTO.UserSearchResults getUsers(com.aspace.ftress.interfaces.ftress.DTO.ALSI alsi, com.aspace.ftress.interfaces.ftress.DTO.ChannelCode channelCode, com.aspace.ftress.interfaces.ftress.DTO.UserCode userCode, com.aspace.ftress.interfaces.ftress.DTO.SecurityDomain securityDomain) throws java.rmi.RemoteException, com.aspace.ftress.interfaces.ftress.DTO.exception.InternalException, com.aspace.ftress.interfaces.ftress.DTO.exception.ObjectNotFoundException, com.aspace.ftress.interfaces.ftress.DTO.exception.NoFunctionPrivilegeException, com.aspace.ftress.interfaces.ftress.DTO.exception.InvalidParameterException, com.aspace.ftress.interfaces.ftress.DTO.exception.ALSIInvalidException;
    public com.aspace.ftress.interfaces.ftress.DTO.User getUser(com.aspace.ftress.interfaces.ftress.DTO.ALSI alsi, com.aspace.ftress.interfaces.ftress.DTO.ChannelCode channelCode, com.aspace.ftress.interfaces.ftress.DTO.UserCode userCode, com.aspace.ftress.interfaces.ftress.DTO.SecurityDomain securityDomain) throws java.rmi.RemoteException, com.aspace.ftress.interfaces.ftress.DTO.exception.InternalException, com.aspace.ftress.interfaces.ftress.DTO.exception.ObjectNotFoundException, com.aspace.ftress.interfaces.ftress.DTO.exception.NoFunctionPrivilegeException, com.aspace.ftress.interfaces.ftress.DTO.exception.InvalidParameterException, com.aspace.ftress.interfaces.ftress.DTO.exception.ALSIInvalidException;
    public com.aspace.ftress.interfaces.ftress.DTO.User createUser(com.aspace.ftress.interfaces.ftress.DTO.ALSI alsi, com.aspace.ftress.interfaces.ftress.DTO.ChannelCode channelCode, com.aspace.ftress.interfaces.ftress.DTO.User user, com.aspace.ftress.interfaces.ftress.DTO.SecurityDomain securityDomain) throws java.rmi.RemoteException, com.aspace.ftress.interfaces.ftress.DTO.exception.InternalException, com.aspace.ftress.interfaces.ftress.DTO.exception.ObjectNotFoundException, com.aspace.ftress.interfaces.ftress.DTO.exception.NoFunctionPrivilegeException, com.aspace.ftress.interfaces.ftress.DTO.exception.CreateDuplicateException, com.aspace.ftress.interfaces.ftress.DTO.exception.InvalidParameterException, com.aspace.ftress.interfaces.ftress.DTO.exception.ALSIInvalidException;
    public void updateUserAttributes(com.aspace.ftress.interfaces.ftress.DTO.ALSI alsi, com.aspace.ftress.interfaces.ftress.DTO.ChannelCode channelCode, com.aspace.ftress.interfaces.ftress.DTO.UserCode userCode, com.aspace.ftress.interfaces.ftress.DTO.Attribute[] attributes, com.aspace.ftress.interfaces.ftress.DTO.SecurityDomain securityDomain) throws java.rmi.RemoteException, com.aspace.ftress.interfaces.ftress.DTO.exception.InternalException, com.aspace.ftress.interfaces.ftress.DTO.exception.ObjectNotFoundException, com.aspace.ftress.interfaces.ftress.DTO.exception.NoFunctionPrivilegeException, com.aspace.ftress.interfaces.ftress.DTO.exception.InvalidParameterException, com.aspace.ftress.interfaces.ftress.DTO.exception.ALSIInvalidException;
    public void deleteUser(com.aspace.ftress.interfaces.ftress.DTO.ALSI alsi, com.aspace.ftress.interfaces.ftress.DTO.ChannelCode channelCode, com.aspace.ftress.interfaces.ftress.DTO.UserCode userCode, com.aspace.ftress.interfaces.ftress.DTO.SecurityDomain securityDomain) throws java.rmi.RemoteException, com.aspace.ftress.interfaces.ftress.DTO.exception.InternalException, com.aspace.ftress.interfaces.ftress.DTO.exception.ObjectNotFoundException, com.aspace.ftress.interfaces.ftress.DTO.exception.NoFunctionPrivilegeException, com.aspace.ftress.interfaces.ftress.DTO.exception.InvalidParameterException, com.aspace.ftress.interfaces.ftress.DTO.exception.ALSIInvalidException;
    public void deleteUsers(com.aspace.ftress.interfaces.ftress.DTO.ALSI alsi, com.aspace.ftress.interfaces.ftress.DTO.ChannelCode channelCode, com.aspace.ftress.interfaces.ftress.DTO.UserCode[] userCode, com.aspace.ftress.interfaces.ftress.DTO.SecurityDomain securityDomain) throws java.rmi.RemoteException, com.aspace.ftress.interfaces.ftress.DTO.exception.InternalException, com.aspace.ftress.interfaces.ftress.DTO.exception.ObjectNotFoundException, com.aspace.ftress.interfaces.ftress.DTO.exception.NoFunctionPrivilegeException, com.aspace.ftress.interfaces.ftress.DTO.exception.InvalidParameterException, com.aspace.ftress.interfaces.ftress.DTO.exception.ALSIInvalidException;
    public com.aspace.ftress.interfaces.ftress.DTO.ContactHistory[] getContactHistory(com.aspace.ftress.interfaces.ftress.DTO.ALSI alsi, com.aspace.ftress.interfaces.ftress.DTO.ChannelCode channelCode, com.aspace.ftress.interfaces.ftress.DTO.UserCode externalReference, com.aspace.ftress.interfaces.ftress.DTO.SecurityDomain securityDomain) throws java.rmi.RemoteException, com.aspace.ftress.interfaces.ftress.DTO.exception.InternalException, com.aspace.ftress.interfaces.ftress.DTO.exception.ObjectNotFoundException, com.aspace.ftress.interfaces.ftress.DTO.exception.NoFunctionPrivilegeException, com.aspace.ftress.interfaces.ftress.DTO.exception.InvalidParameterException, com.aspace.ftress.interfaces.ftress.DTO.exception.ALSIInvalidException;
    public com.aspace.ftress.interfaces.ftress.DTO.UserSearchResults searchUsers(com.aspace.ftress.interfaces.ftress.DTO.ALSI alsi, com.aspace.ftress.interfaces.ftress.DTO.ChannelCode channelCode, com.aspace.ftress.interfaces.ftress.DTO.UserSearchCriteria searchCriteria, com.aspace.ftress.interfaces.ftress.DTO.SecurityDomain securityDomain) throws java.rmi.RemoteException, com.aspace.ftress.interfaces.ftress.DTO.exception.InternalException, com.aspace.ftress.interfaces.ftress.DTO.exception.ObjectNotFoundException, com.aspace.ftress.interfaces.ftress.DTO.exception.NoFunctionPrivilegeException, com.aspace.ftress.interfaces.ftress.DTO.exception.InvalidParameterException, com.aspace.ftress.interfaces.ftress.DTO.exception.ALSIInvalidException;
    public void updateUserExternalReference(com.aspace.ftress.interfaces.ftress.DTO.ALSI alsi, com.aspace.ftress.interfaces.ftress.DTO.ChannelCode channelCode, com.aspace.ftress.interfaces.ftress.DTO.UserCode userCode, com.aspace.ftress.interfaces.ftress.DTO.UserCode newRefCode, com.aspace.ftress.interfaces.ftress.DTO.SecurityDomain securityDomain) throws java.rmi.RemoteException, com.aspace.ftress.interfaces.ftress.DTO.exception.InternalException, com.aspace.ftress.interfaces.ftress.DTO.exception.ObjectNotFoundException, com.aspace.ftress.interfaces.ftress.DTO.exception.NoFunctionPrivilegeException, com.aspace.ftress.interfaces.ftress.DTO.exception.CreateDuplicateException, com.aspace.ftress.interfaces.ftress.DTO.exception.InvalidParameterException, com.aspace.ftress.interfaces.ftress.DTO.exception.ALSIInvalidException;
}
