<?xml version="1.0" encoding="utf-8"?>
<!--
   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
  
   Copyright (c) 2007 Sun Microsystems Inc. All Rights Reserved
  
   The contents of this file are subject to the terms
   of the Common Development and Distribution License
   (the License). You may not use this file except in
   compliance with the License.

   You can obtain a copy of the License at
   https://opensso.dev.java.net/public/CDDLv1.0.html or
   opensso/legal/CDDLv1.0.txt
   See the License for the specific language governing
   permission and limitations under the License.

   When distributing Covered Code, include this CDDL
   Header Notice in each file and include the License file
   at opensso/legal/CDDLv1.0.txt.
   If applicable, add the following below the CDDL Header,
   with the fields enclosed by brackets [] replaced by
   your own identifying information:
   "Portions Copyrighted [year] [name of copyright owner]"

   $Id: famsts.wsdl,v 1.10 2009/10/23 21:22:07 mallas Exp $

-->
<wsdl:definitions name="SecurityTokenService" targetNamespace="http://localhost:8080/openfm/SecurityTokenService/" 
                                              xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
                                              xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
                                              xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" 
                                              xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
                                              xmlns:wsap10="http://www.w3.org/2006/05/addressing/wsdl" 
                                              xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" 
                                              xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" 
                                              xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/09/policy/addressing" 
                                              xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
                                              xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" 
                                              xmlns:tns="http://localhost:8080/openfm/SecurityTokenService/" 
                                              xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
                                              xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" 
                                              xmlns:wsa10="http://www.w3.org/2005/08/addressing">
	<wsp:Policy wsu:Id="ISecurityTokenService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:AsymmetricBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:InitiatorToken>
							<wsp:Policy>
								<sp:X509Token sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
									<wsp:Policy>
										<sp:WssX509V3Token10/>
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:InitiatorToken>
						<sp:RecipientToken>
							<wsp:Policy>
								<sp:X509Token sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Always">
									<wsp:Policy>
										<sp:WssX509V3Token10/>
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:RecipientToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256/>
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax/>
							</wsp:Policy>
						</sp:Layout>
<!--
						<sp:IncludeTimestamp/>
-->
						<sp:OnlySignEntireHeadersAndBody/>
					</wsp:Policy>
				</sp:AsymmetricBinding>
				<sp:Wss10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier/>
						<sp:MustSupportRefIssuerSerial/>
					</wsp:Policy>
				</sp:Wss10>
                                <!--sunsp:DisableStreamingSecurity xmlns:sunsp="http://schemas.sun.com/2006/03/wss/server"/-->
                                
				<wspe:Utf816FFFECharacterEncoding xmlns:wspe="http://schemas.xmlsoap.org/ws/2004/09/policy/encoding"/>
				<wsap10:UsingAddressing/>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="ISecurityTokenService_IssueToken_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body/>
					<!--sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing"/>
					<sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing"/>
					<sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing"/>
					<sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing"/>
					<sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing"/>
					<sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing"/>
					<sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing"/-->
				</sp:SignedParts>
				<!--sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body/>
				</sp:EncryptedParts-->
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="ISecurityTokenService_IssueToken_Output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body/>
					<!--sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing"/>
					<sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing"/>
					<sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing"/>
					<sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing"/>
					<sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing"/>
					<sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing"/>
					<sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing"-->
				</sp:SignedParts>
				<!--sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body/>
				</sp:EncryptedParts-->
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	
	<wsdl:types>
		<xsd:schema targetNamespace="http://localhost:8080/openfm/SecurityTokenService/Imports">
			<xsd:import schemaLocation="sts_schema.xsd" namespace="http://schemas.message.com/Message"/>
		</xsd:schema>
	</wsdl:types>

        <wsdl:message name="ISecurityTokenService_IssueToken_InputMessage">
            <wsdl:part name="rstMessage" type="q1:RequestSecurityToken" 
            xmlns:q1="http://docs.oasis-open.org/ws-sx/ws-trust/200512"/>
        </wsdl:message>
        <wsdl:message name="ISecurityTokenService_IssueToken_OutputMessage">
            <wsdl:part name="ProcessRequestSecurityTokenResult" 
            type="q2:RequestSecurityTokenResponse" xmlns:q2="http://docs.oasis-open.org/ws-sx/ws-trust/200512"/>
        </wsdl:message>

        <wsdl:portType name="ISecurityTokenService">
                <wsdl:operation name="IssueToken">
                        <wsdl:input wsap10:Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue" message="tns:ISecurityTokenService_IssueToken_InputMessage"/>
                        <wsdl:output wsap10:Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RSTR/Issue" message="tns:ISecurityTokenService_IssueToken_OutputMessage"/>
                </wsdl:operation>
        </wsdl:portType>
        <wsdl:binding name="ISecurityTokenService_Binding" type="tns:ISecurityTokenService">
                <wsp:PolicyReference URI="#ISecurityTokenService_policy"/>
                <soap12:binding transport="http://schemas.xmlsoap.org/soap/http"/>
                <wsdl:operation name="IssueToken">
                        <soap12:operation soapAction="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue" style="document"/>
                        <wsdl:input>
                                <wsp:PolicyReference URI="#ISecurityTokenService_IssueToken_Input_policy"/>
                                <soap12:body use="literal"/>
                        </wsdl:input>
                        <wsdl:output>
                                <wsp:PolicyReference URI="#ISecurityTokenService_IssueToken_Output_policy"/>
                                <soap12:body use="literal"/>
                        </wsdl:output>
                </wsdl:operation>
        </wsdl:binding>
        <wsdl:binding name="ISecurityTokenService_BindingSoap11" type="tns:ISecurityTokenService">
                 <wsp:PolicyReference URI="#ISecurityTokenService_policy"/>
                 <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
                 <wsdl:operation name="IssueToken">
                         <soap:operation soapAction="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue" style="document"/>
                         <wsdl:input>
                                 <wsp:PolicyReference URI="#ISecurityTokenService_IssueToken_Input_policy"/>
                                 <soap:body use="literal"/>
                         </wsdl:input>
                         <wsdl:output>
                                 <wsp:PolicyReference URI="#ISecurityTokenService_IssueToken_Output_policy"/>
                                 <soap:body use="literal"/>
                         </wsdl:output>
                 </wsdl:operation>
        </wsdl:binding>
	<wsdl:service name="SecurityTokenService">
                <wsdl:port name="ISecurityTokenService_Port" binding="tns:ISecurityTokenService_Binding">
                        <soap12:address location="http://localhost:8080/opensso/sts"/>
                </wsdl:port>
                <wsdl:port name="ISecurityTokenService_PortSoap11" binding="tns:ISecurityTokenService_BindingSoap11">
                        <soap:address location="http://localhost:8080/opensso/sts/soap11"/>
                 </wsdl:port>
        </wsdl:service>
</wsdl:definitions>
