////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.
 
  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.
 
  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions copyright [year] [name of copyright owner]".
 
  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024-2025 3A Systems LLC.
////

:figure-caption!:
:example-caption!:
:table-caption!:


[#chap-extending]
== Extending OpenAM

OpenAM services solve a wide range of access and federation management problems out of the box. Yet, OpenAM also exposes APIs and SPIs that enable you extend OpenAM services when built-in functionality does not fit your deployment.

This part of the guide covers OpenAM mechanisms for plugging in additional functionality not available out of the box.

[#sec-post-auth]
=== Creating a Post Authentication Plugin

Post authentication plugins (PAP) let you include custom processing at the end of the authentication process, immediately before the subject is authenticated. Common uses of post authentication plugins include setting cookies and session variables. Post authentication plugins are often used in conjunction with policy agents. The post authentication plugin sets custom session properties, and then the policy agent injects the custom properties into the request header to the protected application.

Two issues should be considered when writing a post authentication plugin for an OpenAM deployment that uses stateless sessions:
--

Cookie size::
You can set an unlimited number of session properties in a post authentication plugin. When OpenAM creates a stateless session, it writes the session properties into the session cookie, increasing the size of the cookie. Very large session cookies can exceed browser limitations. Therefore, when implementing a post authentication plugin in a deployment with stateless sessions, be sure to monitor the session cookie size and verify that you have not exceeded browser cookie size limits.

+
For more information about stateless session cookies, see xref:../admin-guide/chap-session-state.adoc#session-state-cookies["Session Cookies"] in the __Administration Guide__.

Cookie security::
The OpenAM administrator secures custom session properties residing on the OpenAM server for stateful sessions by using firewalls and other typical security techniques.

+
However, when using stateless sessions, custom session properties are written in cookies and reside on end users' systems. Cookies can be long-lasting and might represent a security issue if any session properties are of a sensitive nature. When developing a post authentication plugin for a deployment that uses stateless sessions, be sure that you are aware of the measures securing the session contained within the cookie.

+
For more information about stateless session cookie security, see xref:../admin-guide/chap-session-state.adoc#session-state-stateless-cookie-security["Stateless Session Cookie Security"] in the __Administration Guide__.

--
This section explains how to create a post authentication plugin.

[#design-post-authentication-plugin]
==== Designing Your Post Authentication Plugin

Your post authentication plugin class implements the `AMPostAuthProcessInterface` interface, and in particular the following three methods.

[source, java]
----
public void onLoginSuccess(
  Map requestParamsMap,
  HttpServletRequest request,
  HttpServletResponse response,
  SSOToken token
) throws AuthenticationException

public void onLoginFailure(
  Map requestParamsMap,
  HttpServletRequest request,
  HttpServletResponse response
) throws AuthenticationException

public void onLogout(
  HttpServletRequest request,
  HttpServletResponse response,
  SSOToken token
) throws AuthenticationException
----
OpenAM calls the `onLoginSuccess()` and `onLoginFailure()` methods immediately before informing the user of login success or failure, respectively. OpenAM calls the `onLogout()` method only when the user actively logs out, not when a user's session times out.

See the link:../apidocs[OpenAM Java SDK API Specification, window=\_blank] for reference.

These methods can perform whatever processing you require. Yet, know that OpenAM calls your methods synchronously as part of the authentication process. Therefore, if your methods take a long time to complete, you will keep users waiting. Minimize the processing done in your post authentication methods.


[#build-post-authentication-plugin]
==== Building Your Sample Post Authentication Plugin

The following example post authentication plugin sets a session property during successful login, writing to its debug log if the operation fails.

[source, java]
----
package com.forgerock.openam.examples;

import java.util.Map;

import com.iplanet.sso.SSOException;
import com.iplanet.sso.SSOToken;

import com.sun.identity.authentication.spi.AMPostAuthProcessInterface;
import com.sun.identity.authentication.spi.AuthenticationException;
import com.sun.identity.shared.debug.Debug;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

public class SamplePAP implements AMPostAuthProcessInterface {
    private final static String PROP_NAME = "MyProperty";
    private final static String PROP_VALUE = "MyValue";
    private final static String DEBUG_FILE = "SamplePAP";

    protected Debug debug = Debug.getInstance(DEBUG_FILE);

    public void onLoginSuccess(
            Map requestParamsMap,
            HttpServletRequest request,
            HttpServletResponse response,
            SSOToken token
    ) throws AuthenticationException {
        try {
            token.setProperty(PROP_NAME, PROP_VALUE);
        } catch (SSOException e) {
            debug.error("Unable to set property");
        }
    }

    public void onLoginFailure(
            Map requestParamsMap,
            HttpServletRequest request,
            HttpServletResponse response
    ) throws AuthenticationException {
        // Not used
    }

    public void onLogout(
            HttpServletRequest request,
            HttpServletResponse response,
            SSOToken token
    ) throws AuthenticationException {
        // Not used
    }
}
----
The link:https://github.com/OpenIdentityPlatform/openam-post-auth-sample[sample post authentication plugin source, window=\_blank] is available online. Get a local clone so that you can try the sample on your system. In the sources you find the following files.
--

`pom.xml`::
Apache Maven project file for the module

+
This file specifies how to build the sample post authentication plugin, and also specifies its dependencies on OpenAM components and on the Servlet API.

`src/main/java/com/forgerock/openam/examples/SamplePAP.java`::
Core class for the sample post authentication plugin

--
Build the module using Apache Maven.

[source, console]
----
$ cd /path/to/openam-post-auth-sample
$ mvn install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building openam-post-auth-sample 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------

...

[INFO]
[INFO] --- maven-jar-plugin:2.3.1:jar (default-jar) @ openam-post-auth-sample --
[INFO] Building jar: .../target/openam-post-auth-sample-1.0.0-SNAPSHOT.jar

...

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.727s
[INFO] Finished at: Mon Nov 25 17:07:23 CET 2013
[INFO] Final Memory: 20M/227M
[INFO] ------------------------------------------------------------------------
----
Copy the .jar to the `WEB-INF/lib` directory where you deployed OpenAM.

[source, console]
----
$ cp target/*.jar /path/to/tomcat/webapps/openam/WEB-INF/lib/
----
Restart OpenAM or the container in which it runs.


[#configure-post-authentication-plugin]
==== Configuring Your Post Authentication Plugin

You can associate post authentication plugins with realms or services (authentication chains). Where you configure the plugin depends on the scope to which the plugin should apply:

* Plugins configured at the realm level are executed when authenticating to any authentication chain in the realm, provided the authentication chain does not have an associated plugin.

* Plugins configured at the service level are executed if that authentication chain is used for authentication. Any plugins configured at the realm level will not execute.

In OpenAM Console, navigate to Realms > __Realm Name__ > Authentication > Settings > Post Authentication Processing. In the Authentication Post Processing Classes list, add the sample plugin class, `com.forgerock.openam.examples.SamplePAP`, and then click Save.

Alternatively, you can configure sample plugin for the realm by using the `ssoadm` command.

[source, console]
----
$ ssoadm
  set-svc-attrs
  --adminid amadmin
  --password-file /tmp/pwd.txt
  --servicename iPlanetAMAuthService
  --realm /myRealm
  --attributevalues iplanet-am-auth-post-login-process-class=
  com.forgerock.openam.examples.SamplePAP

iPlanetAMAuthService under /myRealm was
  modified.
----


[#test-post-authentication-plugin]
==== Testing Your Post Authentication Plugin

To test the sample post authentication plugin, login successfully to OpenAM in the scope where the plugin is configured. For example, if you configured your plugin for the realm, `/myRealm`, specify the realm in the login URL.

[source]
----
http://openam.example.com:8080/openam/UI/Login?realm=myRealm
----
Although as a user you do not notice anywhere in the user interface that OpenAM calls your plugin, a policy agent or custom client code could retrieve the session property that your plugin added to the user session.



[#sec-uma-extension-points]
=== Extending UMA Workflow with Extension Points

OpenAM provides a number of extension points for extending the UMA workflow. These extension points are provided as filters and are dynamically loaded by using the link:http://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html[Java ServiceLoader framework, window=\_top] during the UMA workflow.

The extension points available are described in the sections below:

* xref:#ext-resource-registration["Resource Set Registration Extension Point"]

* xref:#ext-permission-requests["Permission Request Extension Point"]

* xref:#ext-authorization-requests["Authorization Request Extension Point"]

* xref:#ext-resource-delegation["Resource Sharing Extension Point"]


[#ext-resource-registration]
==== Resource Set Registration Extension Point

OpenAM provides the `ResourceRegistrationFilter` extension point, which can be used to extend UMA resource set registration functionality.

[#ext-resource-registration-methods]
.Resource Set Registration Extension Methods
[cols="33%,33%,34%"]
|===
|Method |Parameters |Description 

a|`beforeResourceRegistration`
a|__resourceSet__ (type: `ResourceSetDescription`)
a|Invoked before a resource set is registered in the backend.

 Changes made to the __resourceSet__ object at this stage __will__ be persisted.

a|`afterResourceRegistration`
a|__resourceSet__ (type: `ResourceSetDescription`)
a|Invoked after a resource set is registered in the backend.

 Changes made to the __resourceSet__ object at this stage __will not__ be persisted.
|===


[#ext-permission-requests]
==== Permission Request Extension Point

OpenAM provides the `PermissionRequestFilter` extension point, which can be used to extend UMA permission request functionality.

[#ext-permission-requests-methods]
.Permission Request Extension Methods
[cols="33%,33%,34%"]
|===
|Method |Parameters |Description 

a|`onPermissionRequest`
a|__resourceSet__ (type: `ResourceSetDescription`)

 __requestedScopes__ (type: `Set<String>`)

 __requestingClientId__ (type: `String`)
a|Invoked before a permission request is created.
|===


[#ext-authorization-requests]
==== Authorization Request Extension Point

OpenAM provides the `RequestAuthorizationFilter` extension point, which can be used to extend UMA authorization functionality.

[#ext-authorization-requests-methods]
.Authorization Request Extension Methods
[cols="33%,33%,34%"]
|===
|Method |Parameters |Description 

a|`beforeAuthorization`
a|__permissionTicket__ (type: `PermissionTicket`)

 __requestingParty__ (type: `Subject`)

 __resourceOwner__ (type: `Subject`)
a|Invoked before authorization of a request is attempted.

 Throws `UmaException` if authorization of the request should not be attempted.

a|`afterAuthorization`
a|__isAuthorized__ (type: `boolean`)

 __permissionTicket__ (type: `PermissionTicket`)

 __requestingParty__ (type: `Subject`)

 __resourceOwner__ (type: `Subject`)
a|Invoked before authorization of a request is attempted.

 If the authorization request was successful, __isAuthorized__ will be `true`.
|===


[#ext-resource-delegation]
==== Resource Sharing Extension Point

OpenAM provides the `ResourceDelegationFilter` extension point, which can be used to extend UMA resource sharing functionality.

[#ext-resource-delegation-methods]
.Resource Sharing Extension Methods
[cols="40%,33%,27%"]
|===
|Method |Parameters |Description 

a|`beforeResourceShared`
a|__umaPolicy__ (type: `UmaPolicy`)
a|Invoked before creating a sharing policy for a resource.

 Changes to the __umaPolicy__ object at this stage __will__ be persisted.

 Throws `ResourceException` if a sharing policy for the resource should not be created.

a|`afterResourceShared`
a|__umaPolicy__ (type: `UmaPolicy`)
a|Invoked after creating a sharing policy for a resource.

 Changes to the __umaPolicy__ object at this stage __will not__ be persisted.

a|`beforeResourceSharedModification`
a|__currentUmaPolicy__ (type: `UmaPolicy`)

 __updatedUmaPolicy__ (type: `UmaPolicy`)
a|Invoked before altering the sharing policy of a resource.

 Changes to the __updatedUmaPolicy__ object at this stage __will__ be persisted.

 Throws `ResourceException` if the sharing policy of the resource should not be modified.

a|`onResourceSharedDeletion`
a|__umaPolicy__ (type: `UmaPolicy`)
a|Invoked before deleting the sharing policy of a resource.

 Throws `ResourceException` if the sharing policy of the resource should not be deleted.

a|`beforeQueryResourceSets`
a|__userId__ (type: `String`)

 __queryFilter__ (type: `QueryFilter<JsonPointer>`)
a|Invoked before querying the resource sets owned or shared with a user.

 The __userId__ parameter provides the ID of the user making the query request.

 The __queryFilter__ parameter provides the incoming request query filter.

 Returns a `QueryFilter` that can be used to return the user's resource sets.
|===



