#!/bin/sh

# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2008 Sun Microsystems Inc. All Rights Reserved
#
# The contents of this file are subject to the terms
# of the Common Development and Distribution License
# (the License). You may not use this file except in
# compliance with the License.
#
# You can obtain a copy of the License at
# https://opensso.dev.java.net/public/CDDLv1.0.html or
# opensso/legal/CDDLv1.0.txt
# See the License for the specific language governing
# permission and limitations under the License.
#
# When distributing Covered Code, include this CDDL
# Header Notice in each file and include the License file
# at opensso/legal/CDDLv1.0.txt.
# If applicable, add the following below the CDDL Header,
# with the fields enclosed by brackets [] replaced by
# your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
#
# $Id: ssoadm,v 1.20 2010/01/28 00:49:05 bigfatrat Exp $
#

# Portions Copyrighted 2010-2015 ForgeRock AS.

if [ -z "$JAVA_HOME" ] ; then
    JAVA_HOME="\@JAVA_HOME@"
fi

TOOLS_HOME="@TOOLS_HOME@"
EXT_CLASSPATH=$CLASSPATH

LIB_CP=
for JAR in ${TOOLS_HOME}/lib/*.jar; do
    LIB_CP=${LIB_CP}:${JAR}
done

CLASSPATH="@CONFIG_DIR@"
CLASSPATH="$CLASSPATH:$TOOLS_HOME/classes:$TOOLS_HOME/resources"
CLASSPATH="$CLASSPATH:$LIB_CP"

if [ -n "$EXT_CLASSPATH" ] ; then
    CLASSPATH=$EXT_CLASSPATH:$CLASSPATH
fi

if [ "$1" == "-debug" ] ; then
    DEBUG="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=9897"
    shift
fi

$JAVA_HOME/bin/java -Xms64m -Xmx256m -cp "$CLASSPATH" $DEBUG \
    org.forgerock.audit.handlers.csv.CsvSecureArchiveVerifierCli "$@"
