//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.14 at 08:50:29 AM PST 
//


package com.sun.identity.entitlement.xacml3.core;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for MatchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatchType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:3.0:core:schema:wd-17}AttributeValue"/>
 *         &lt;choice>
 *           &lt;element ref="{urn:oasis:names:tc:xacml:3.0:core:schema:wd-17}AttributeDesignator"/>
 *           &lt;element ref="{urn:oasis:names:tc:xacml:3.0:core:schema:wd-17}AttributeSelector"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="MatchId" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatchType", propOrder = {
    "attributeValue",
    "attributeDesignator",
    "attributeSelector"
})
public class Match {

    @XmlElement(name = "AttributeValue", required = true)
    protected AttributeValue attributeValue;
    @XmlElement(name = "AttributeDesignator")
    protected AttributeDesignator attributeDesignator;
    @XmlElement(name = "AttributeSelector")
    protected AttributeSelector attributeSelector;
    @XmlAttribute(name = "MatchId", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String matchId;

    /**
     * Gets the value of the attributeValue property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeValue }
     *
     */
    public AttributeValue getAttributeValue() {
        return attributeValue;
    }

    /**
     * Sets the value of the attributeValue property.
     *
     * @param value
     *     allowed object is
     *     {@link AttributeValue }
     *
     */
    public void setAttributeValue(AttributeValue value) {
        this.attributeValue = value;
    }

    /**
     * Gets the value of the attributeDesignator property.
     *
     * @return
     *     possible object is
     *     {@link AttributeDesignator }
     *
     */
    public AttributeDesignator getAttributeDesignator() {
        return attributeDesignator;
    }

    /**
     * Sets the value of the attributeDesignator property.
     *
     * @param value
     *     allowed object is
     *     {@link AttributeDesignator }
     *
     */
    public void setAttributeDesignator(AttributeDesignator value) {
        this.attributeDesignator = value;
    }

    /**
     * Gets the value of the attributeSelector property.
     *
     * @return
     *     possible object is
     *     {@link AttributeSelector }
     *
     */
    public AttributeSelector getAttributeSelector() {
        return attributeSelector;
    }

    /**
     * Sets the value of the attributeSelector property.
     *
     * @param value
     *     allowed object is
     *     {@link AttributeSelector }
     *     
     */
    public void setAttributeSelector(AttributeSelector value) {
        this.attributeSelector = value;
    }

    /**
     * Gets the value of the matchId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchId() {
        return matchId;
    }

    /**
     * Sets the value of the matchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchId(String value) {
        this.matchId = value;
    }

}
