////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.
 
  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.
 
  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions copyright [year] [name of copyright owner]".
 
  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.
////

:figure-caption!:
:example-caption!:
:table-caption!:


[#chap-websphere]
== Installing Java EE Agents in IBM WebSphere

This chapter covers installation of the policy agent for IBM WebSphere.

[#before-websphere-agent-install]
=== Before You Install

Make sure OpenAM is installed and running, and that you can contact OpenAM from the system running the policy agent. Next, create a profile for your policy agent as described in xref:../jee-users-guide/chap-jee-agent-config.adoc#create-agent-profiles[Creating Agent Profiles]. To protect resources with the agent, create at least one policy as described in link:../../../openam/13/admin-guide/#chap-authz-policy[Configuring Policies, window=\_blank] in the __OpenAM Administration Guide__. Consider creating a simple policy, such as a policy that allows only authenticated users to access your resources in order to test your policy agent after installation.

You must install WebSphere before you install the policy agent, and you must stop the server during installation.

You must install a supported version of the Java runtime environment. Set the `JAVA_HOME` environment variable accordingly. The policy agent installer requires Java.

[source, console]
----
$ echo $JAVA_HOME
/path/to/java
----
If you are using IBM Java, see xref:#install-with-ibm-jvm[To Install With IBM Java].

See the OpenAM __Installation Guide__ section, link:../../../openam/13/install-guide/#download-openam-software[Obtaining OpenAM Software, window=\_blank] to determine which version of the agent to download, and download the agent. Also verify the checksum of the file you download against the checksum posted on the download page.

Unzip the file in the directory where you plan to install the J2EE policy agent. The agent you install stores its configuration and logs under this directory.

When you unzip the policy agent, you find the following directories under the `j2ee_agents/websphere_v61_agent` directory.

Despite the directory name, the policy agent supports multiple container versions.
--

`bin`::
The installation and configuration program `agentadmin`. For more details about the available command-line tools, see xref:tools-reference.adoc#tools-reference[Command-Line Tool Reference].

`config`::
Configuration templates used by the `agentadmin` command during installation

`data`::
Not used

`etc`::
Configuration templates used during installation

`installer-logs`::
Location for log files written during installation

`legal-notices`::
Contains licensing information including third-party licenses

`lib`::
Shared libraries used by the Java EE policy agent

`locale`::
Property files used by the installation program

`README`::
README file containing platform and install information for the agent

--

[#install-with-ibm-jvm]
.To Install With IBM Java
====
The WebSphere policy agent runs with IBM Java. To install the policy agent using IBM Java on platforms other than AIX, you must change the `agentadmin` script to use the IBM Java Cryptography Extensions (JCE).

Note that line breaks and continuation marker (*\*) characters have been manually added to the following examples to aid display in the documentation. These are not required when editing the script file.

. Open the file, `bin/agentadmin` for editing.

. Remove the `if` statement surrounding the line defining the `AGENT_OPTS` environment variable for AIX platforms:
+
Before:
+

[source, sh]
----
if [ "$OS_TYPE" = "AIX" ]; then
    AGENT_OPTS="-DamKeyGenDescriptor.provider=IBMJCE \
                -DamCryptoDescriptor.provider=IBMJCE \
                -DamRandomGenProvider=IBMJCE"
else
    AGENT_OPTS=
fi
----
+
After:
+

[source, sh]
----
AGENT_OPTS="-DamKeyGenDescriptor.provider=IBMJCE \
                -DamCryptoDescriptor.provider=IBMJCE \
                -DamRandomGenProvider=IBMJCE"
----

. Edit the line that calls the `AdminToolLauncher` to move the `$AGENT_OPTS` environment variable before the classpath is set:
+
Before:
+

[source, sh]
----
$JAVA_VM -classpath "$AGENT_CLASSPATH" $AGENT_OPTS \
    com.sun.identity.install.tools.launch.AdminToolLauncher $*
----
+
After:
+

[source, sh]
----
$JAVA_VM $AGENT_OPTS -classpath "$AGENT_CLASSPATH" \
    com.sun.identity.install.tools.launch.AdminToolLauncher $*
----

. Save your work.
+
You can now install the WebSphere policy agent with IBM Java as described in xref:#install-websphere-agent[Installing the WebSphere Policy Agent].

====


[#install-websphere-agent]
=== Installing the WebSphere Policy Agent

Complete the following procedures to install the policy agent.

[#d0e6866]
.To Create the Agent Profile
====
Regardless of whether you store configurations centrally in OpenAM or locally with your agents, the agent requires a profile so that it can connect to and communicate with OpenAM.

. In the OpenAM console, browse to Realms > __Realm Name__ > Agents > J2EE, and then click the New... button in the Agent table.

. Complete the web form using the following hints:
+
--

Name::
The name for the agent profile used when you install the agent

Password::
Password the agent uses to authenticate to OpenAM

Configuration::
Centralized configurations are stored in the OpenAM configuration store. You can manage the centralized configuration through the OpenAM console. Local configurations are stored in a file alongside the agent.

Server URL::
The full URL to an OpenAM instance, or if OpenAM is deployed in a site configuration (behind a load balancer) then the site URL
+
In centralized configuration mode, the Server URL is used to populate the agent profile for services, such as Login, Logout, Naming, and Cross Domain SSO.

Agent URL::
The URL to the J2EE agent application, such as `\http://www.example.com:8080/agentapp`
+
In centralized configuration mode, the Agent URL is used to populate the Agent Profile for services, such as notifications.

--

====

[#d0e6918]
.To Create a Password File
====

. Create a text file containing only the password specified when creating the agent profile.
+
UNIX example:
+

[source, console]
----
$ echo password > /tmp/pwd.txt
----
+
Windows example:
+

[source, console]
----
C:\> echo password > pwd.txt
----

. Protect the password file you create as appropriate for your operating system:
+
UNIX example:
+

[source, console]
----
$ chmod 400 /tmp/pwd.txt
----
+
Windows example:
+
In Windows Explorer, right-click the created password file, for example `pwd.txt`, select Read-Only, and then click OK.

====

[#install-agent-into-websphere]
.To Install the Policy Agent into WebSphere
====

. Shut down the WebSphere server where you plan to install the agent.

. Make sure OpenAM is running.

. Run `agentadmin --install` to install the agent.
+
When you run the command, you will be prompted to read and accept the software license agreement for the agent installation. You can suppress the license agreement prompt by including the `--acceptLicence` parameter. The inclusion of the option indicates that you have read and accepted the terms stated in the license. To view the license agreement, open `<server-root>/legal-notices/license.txt`.
+

[source, console]
----
$ /path/to/j2ee_agents/websphere_v61_agent/bin/agentadmin --install \
  --acceptLicense
...
-----------------------------------------------
SUMMARY OF YOUR RESPONSES
-----------------------------------------------
Instance Config Directory :
/path/to/WebSphere/AppServer/profiles/AppSrv01/config/cells/wwwNode01Cell/
 nodes/wwwNode01/servers/server1

Instance Server name : server1
WebSphere Install Root Directory : /path/to/WebSphere/AppServer
OpenAM server URL : http://openam.example.com:8080/openam
Agent URL : http://www.example.com:9080/agentapp
Agent Profile name : WebSphere Agent
Agent Profile Password file name : /tmp/pwd.txt

...
SUMMARY OF AGENT INSTALLATION
-----------------------------
Agent instance name: Agent_001
Agent Bootstrap file location:
/path/to/j2ee_agents/websphere_v61_agent/Agent_001/config/
 OpenSSOAgentBootstrap.properties
Agent Configuration file location
/path/to/j2ee_agents/websphere_v61_agent/Agent_001/config/
 OpenSSOAgentConfiguration.properties
Agent Audit directory location:
/path/to/j2ee_agents/websphere_v61_agent/Agent_001/logs/audit
Agent Debug directory location:
/path/to/j2ee_agents/websphere_v61_agent/Agent_001/logs/debug


Install log file location:
/path/to/j2ee_agents/websphere_v61_agent/installer-logs/audit/install.log
...
----
+
Upon successful completion, the installer updates the WebSphere configuration, copies the agent libraries to WebSphere's external library directory, and also sets up configuration and log directories for the agent.
+

[NOTE]
======
If the agent is in a different domain than the server, refer to the __Administration Guide__ procedure, link:../../../openam/13/admin-guide/#chap-cdsso[Configuring Cross-Domain Single Sign On, window=\_blank].
======

. Take note of the configuration files and log locations.
+
Each agent instance that you install on the system has its own numbered configuration and logs directory. The first agent's configuration and logs are thus located under the directory `j2ee_agents/websphere_v61_agent/Agent_001/`:
+
--

`config/OpenSSOAgentBootstrap.properties`::
Used to bootstrap the Java EE policy agent, allowing the agent to connect to OpenAM and download its configuration.

`config/OpenSSOAgentConfiguration.properties`::
Only used if you configured the Java EE policy agent to use local configuration.

`logs/audit/`::
Operational audit log directory, only used if remote logging to OpenAM is disabled.

`logs/debug/`::
Debug directory where the debug file resides. Useful in troubleshooting policy agent issues.

--

. If your policy agent configuration is not in the top-level realm (/), then you must edit config/OpenSSOAgentBootstrap.properties to identify the sub-realm that has your policy agent configuration. Find com.sun.identity.agents.config.organization.name and change the / to the path to your policy agent profile. This allows the policy agent to properly identify itself to the OpenAM server.

. Restart the WebSphere server.

====

[#protect-websphere-apps-after-agent-installation]
.To Protect Applications After Agent Installation
====

. (Optional) Deploy the `/path/to/j2ee_agents/websphere_v61_agent/etc/agentapp.war` agent application in WebSphere.
+
The `agentapp.war` application is required to enable notifications. If you decide not to deploy the application, you may want to enable the `com.sun.identity.agents.config.load.interval` property to allow the agent to fetch configuration changes from OpenAM.

. For each web application to protect, add the following filter to the application's `WEB-INF/web.xml` deployment descriptor, following the opening <web-app> tag:
+

[source, xml]
----
<filter>
  <filter-name>Agent</filter-name>
  <display-name>Agent</display-name>
  <description>OpenAM Policy Agent Filter</description>
 <filter-class>com.sun.identity.agents.filter.AmAgentFilter</filter-class>
 </filter>
 <filter-mapping>
  <filter-name>Agent</filter-name>
  <url-pattern>/*</url-pattern>
  <dispatcher>REQUEST</dispatcher>
  <dispatcher>INCLUDE</dispatcher>
  <dispatcher>FORWARD</dispatcher>
  <dispatcher>ERROR</dispatcher>
 </filter-mapping>
----
+
You might also have to update additional configuration files. See the sample application located under `/path/to/j2ee_agents/websphere_v61_agent/sampleapp` for examples.

. (Optional) If you have a policy configured, you can test your policy agent. For example, try to browse to a resource that your policy agent protects. You should be redirected to OpenAM to authenticate, for example, as user `demo`, password `changeit`. After you authenticate, OpenAM then redirects you back to the resource you tried to access.

====


[#silent-websphere-agent-installation]
=== Silent WebSphere Policy Agent Installation

When performing a scripted, silent installation, use `agentadmin --install --saveResponse response-file` to create a response file for scripted installation. Then install silently using `agentadmin --install --acceptLicense --useResponse response-file`.


[#uninstall-websphere-agent]
=== Removing WebSphere Policy Agent Software

Shut down the WebSphere server before you uninstall the policy agent.

To remove the Java EE policy agent, use `agentadmin --uninstall`. You must provide the WebSphere configuration directory location.

Uninstall does not remove the agent instance directory, but you can do so manually after removing the agent configuration from WebSphere.


[#websphere-network-deployment]
=== Notes About WebSphere Network Deployment

When using WebSphere Application Server Network Deployment, you must install policy agents on the Deployment Manager, on each Node Agent, and on each Application Server. Installation requires that you stop and then restart the Deployment Manager, each Node Agent, and each Application Server in the Network Deployment.

Before installation, synchronize each server configuration with the profile saved by the Deployment Manager using the `syncNode` command. After agent installation, copy the server configuration for each node stored in `server.xml` to the corresponding Deployment Manager profile. After you have synchronized the configurations, you must restart the Deployment Manager for the Network Deployment.


