#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2013 ForgeRock Inc. All Rights Reserved
#
# The contents of this file are subject to the terms
# of the Common Development and Distribution License
# (the License). You may not use this file except in
# compliance with the License.
#
# You can obtain a copy of the License at
# http://forgerock.org/license/CDDLv1.0.html
# See the License for the specific language governing
# permission and limitations under the License.
#
# When distributing Covered Code, include this CDDL
# Header Notice in each file and include the License file
# at http://forgerock.org/license/CDDLv1.0.html
# If applicable, add the following below the CDDL Header,
# with the fields enclosed by brackets [] replaced by
# your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
#

CC = cl
LINK = link

SAMPLE_SRC = am_auth_test.c am_sso_test.c am_log_test.c am_policy_test.c am_web_agent_test.c
        
DEP_LIBS = kernel32.lib amsdk.lib

LDFLAGS = /NOLOGO /INCREMENTAL:NO /errorReport:none /MANIFEST:NO \
   /OPT:REF /OPT:ICF /LTCG /DYNAMICBASE /NXCOMPAT /DEBUG \
   /IGNORE:4049 /LIBPATH:"..\lib"\
!IFDEF X64
   /MACHINE:X64
!ELSE
   /MACHINE:X86
!ENDIF

CFLAGS = /O2 /Oi /GL /Gy /D _CRT_SECURE_NO_WARNINGS \
   /wd4996 /wd4101 /wd4244 /wd4995 /wd4275 /EHsc /nologo /Zi /errorReport:none /MP /Gm- /W3 /c /D WIN32 \
   /I"..\include" /MT /D _WIN32_WINNT=0x0502

.c.obj::
	$(CC) $(CFLAGS) $< 

SAMPLE_OBJECTS = $(SAMPLE_SRC:.c=.obj)

all: clean am_auth_test am_sso_test am_policy_test am_log_test am_web_agent_test

am_auth_test: am_auth_test.obj
      $(LINK) $(LDFLAGS) /SUBSYSTEM:CONSOLE /PDB:"am_auth_test.pdb" /OUT:"am_auth_test.exe" am_auth_test.obj $(DEP_LIBS)

am_sso_test: am_sso_test.obj
      $(LINK) $(LDFLAGS) /SUBSYSTEM:CONSOLE /PDB:"am_sso_test.pdb" /OUT:"am_sso_test.exe" am_sso_test.obj $(DEP_LIBS)

am_policy_test: am_policy_test.obj
      $(LINK) $(LDFLAGS) /SUBSYSTEM:CONSOLE /PDB:"am_policy_test.pdb" /OUT:"am_policy_test.exe" am_policy_test.obj $(DEP_LIBS)

am_log_test: am_log_test.obj
      $(LINK) $(LDFLAGS) /SUBSYSTEM:CONSOLE /PDB:"am_log_test.pdb" /OUT:"am_log_test.exe" am_log_test.obj $(DEP_LIBS)

am_web_agent_test: am_web_agent_test.obj
      $(LINK) $(LDFLAGS) /SUBSYSTEM:CONSOLE /PDB:"am_web_agent_test.pdb" /OUT:"am_web_agent_test.exe" am_web_agent_test.obj $(DEP_LIBS)

clean:
      del /F /Q *.obj
      del /F /Q *.exe
      del /F /Q *.pdb