////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.
 
  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.
 
  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions copyright [year] [name of copyright owner]".
 
  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.
////

:figure-caption!:
:example-caption!:
:table-caption!:


[glossary]
[#openam-glossary]
== OpenAM Glossary


Access control::
Control to grant or to deny access to a resource.

Account lockout::
The act of making an account temporarily or permanently inactive after successive authentication failures.

Actions::
Defined as part of policies, these verbs indicate what authorized subjects can do to resources.

Advice::
In the context of a policy decision denying access, a hint to the policy enforcement point about remedial action to take that could result in a decision allowing access.

Agent administrator::
User having privileges only to read and write policy agent profile configuration information, typically created to delegate policy agent profile creation to the user installing a policy agent.

Agent authenticator::
Entity with read-only access to multiple agent profiles defined in the same realm; allows an agent to read web service profiles.

Application::
In general terms, a service exposing protected resources.

+
In the context of OpenAM policies, the application is a template that constrains the policies that govern access to protected resources. An application can have zero or more policies.

Application type::
Application types act as templates for creating policy applications.

+
Application types define a preset list of actions and functional logic, such as policy lookup and resource comparator logic.

+
Application types also define the internal normalization, indexing logic, and comparator logic for applications.

Attribute-based access control (ABAC)::
Access control that is based on attributes of a user, such as how old a user is or whether the user is a paying customer.

Authentication::
The act of confirming the identity of a principal.

Authentication chaining::
A series of authentication modules configured together which a principal must negotiate as configured in order to authenticate successfully.

Authentication level::
Positive integer associated with an authentication module, usually used to require success with more stringent authentication measures when requesting resources requiring special protection.

Authentication module::
OpenAM authentication unit that handles one way of obtaining and verifying credentials.

Authorization::
The act of determining whether to grant or to deny a principal access to a resource.

Authorization Server::
In OAuth 2.0, issues access tokens to the client after authenticating a resource owner and confirming that the owner authorizes the client to access the protected resource. OpenAM can play this role in the OAuth 2.0 authorization framework.

Auto-federation::
Arrangement to federate a principal's identity automatically based on a common attribute value shared across the principal's profiles at different providers.

Bulk federation::
Batch job permanently federating user profiles between a service provider and an identity provider based on a list of matched user identifiers that exist on both providers.

Circle of trust::
Group of providers, including at least one identity provider, who have agreed to trust each other to participate in a SAML v2.0 provider federation.

Client::
In OAuth 2.0, requests protected web resources on behalf of the resource owner given the owner's authorization. OpenAM can play this role in the OAuth 2.0 authorization framework.

Conditions::
Defined as part of policies, these determine the circumstances under which which a policy applies.

+
Environmental conditions reflect circumstances like the client IP address, time of day, how the subject authenticated, or the authentication level achieved.

+
Subject conditions reflect characteristics of the subject like whether the subject authenticated, the identity of the subject, or claims in the subject's JWT.

Configuration datastore::
LDAP directory service holding OpenAM configuration data.

Cross-domain single sign-on (CDSSO)::
OpenAM capability allowing single sign-on across different DNS domains.

Delegation::
Granting users administrative privileges with OpenAM.

Entitlement::
Decision that defines which resource names can and cannot be accessed for a given subject in the context of a particular application, which actions are allowed and which are denied, and any related advice and attributes.

Extended metadata::
Federation configuration information specific to OpenAM.

Extensible Access Control Markup Language (XACML)::
Standard, XML-based access control policy language, including a processing model for making authorization decisions based on policies.

Federation::
Standardized means for aggregating identities, sharing authentication and authorization data information between trusted providers, and allowing principals to access services across different providers without authenticating repeatedly.

Fedlet::
Service provider application capable of participating in a circle of trust and allowing federation without installing all of OpenAM on the service provider side; OpenAM lets you create Java Fedlets.

Hot swappable::
Refers to configuration properties for which changes can take effect without restarting the container where OpenAM runs.

Identity::
Set of data that uniquely describes a person or a thing such as a device or an application.

Identity federation::
Linking of a principal's identity across multiple providers.

Identity provider (IdP)::
Entity that produces assertions about a principal (such as how and when a principal authenticated, or that the principal's profile has a specified attribute value).

Identity repository::
Data store holding user profiles and group information; different identity repositories can be defined for different realms.

Java EE policy agent::
Java web application installed in a web container that acts as a policy agent, filtering requests to other applications in the container with policies based on application resource URLs.

Metadata::
Federation configuration information for a provider.

Policy::
Set of rules that define who is granted access to a protected resource when, how, and under what conditions.

Policy Agent::
Agent that intercepts requests for resources, directs principals to OpenAM for authentication, and enforces policy decisions from OpenAM.

Policy Administration Point (PAP)::
Entity that manages and stores policy definitions.

Policy Decision Point (PDP)::
Entity that evaluates access rights and then issues authorization decisions.

Policy Enforcement Point (PEP)::
Entity that intercepts a request for a resource and then enforces policy decisions from a PDP.

Policy Information Point (PIP)::
Entity that provides extra information, such as user profile attributes that a PDP needs in order to make a decision.

[#def-principal]
Principal::
Represents an entity that has been authenticated (such as a user, a device, or an application), and thus is distinguished from other entities.

+
When a xref:#def-subject[Subject] successfully authenticates, OpenAM associates the Subject with the Principal.

Privilege::
In the context of delegated administration, a set of administrative tasks that can be performed by specified subjects in a given realm.

Provider federation::
Agreement among providers to participate in a circle of trust.

Realm::
OpenAM unit for organizing configuration and identity information.

+
Realms can be used for example when different parts of an organization have different applications and user data stores, and when different organizations use the same OpenAM deployment.

+
Administrators can delegate realm administration. The administrator assigns administrative privileges to users, allowing them to perform administrative tasks within the realm.

Resource::
Something a user can access over the network such as a web page.

+
Defined as part of policies, these can include wildcards in order to match multiple actual resources.

Resource owner::
In OAuth 2.0, entity who can authorize access to protected web resources, such as an end user.

Resource server::
In OAuth 2.0, server hosting protected web resources, capable of handling access tokens to respond to requests for such resources.

Response attributes::
Defined as part of policies, these allow OpenAM to return additional information in the form of "attributes" with the response to a policy decision.

Role based access control (RBAC)::
Access control that is based on whether a user has been granted a set of permissions (a role).

Security Assertion Markup Language (SAML)::
Standard, XML-based language for exchanging authentication and authorization data between identity providers and service providers.

Service provider (SP)::
Entity that consumes assertions about a principal (and provides a service that the principal is trying to access).

Session::
The interval that starts with the user authenticating through OpenAM and ends when the user logs out, or when their session is terminated. For browser-based clients, OpenAM manages user sessions across one or more applications by setting a session cookie. See also xref:#def-stateful-session[Stateful session] and xref:#def-stateless-session[Stateless session].

Session failover (SFO)::
Capability to allow another OpenAM server to manage a session when the OpenAM server that initially authenticated the principal goes offline.

Session token::
Unique identifier issued by OpenAM after successful authentication. For a xref:#def-stateful-session[Stateful session], the session token is used to track a principal's session.

Single log out (SLO)::
Capability allowing a principal to end a session once, thereby ending her session across multiple applications.

Single sign-on (SSO)::
Capability allowing a principal to authenticate once and gain access to multiple applications without authenticating again.

Site::
Group of OpenAM servers configured the same way, accessed through a load balancer layer.

+
The load balancer handles failover to provide service-level availability. Use sticky load balancing based on `amlbcookie` values to minimize cross-talk in the site.

+
The load balancer can also be used to protect OpenAM services.

Standard metadata::
Standard federation configuration information that you can share with other access management software.

[#def-stateful-session]
Stateful session::
An OpenAM session that resides in the OpenAM server's memory and, if session failover is enabled, is also persisted in the Core Token Service's token store. OpenAM tracks stateful sessions in order to handle events like logout and timeout, to permit session constraints, and to notify applications involved in SSO when a session ends.

[#def-stateless-session]
Stateless session::
An OpenAM session for which state information is encoded in OpenAM and stored on the client. The information from the session is not retained in OpenAM's memory. For browser-based clients, OpenAM sets a cookie in the browser that contains the session information.

[#def-subject]
Subject::
Entity that requests access to a resource

+
When a subject successfully authenticates, OpenAM associates the subject with the xref:#def-principal[Principal] that distinguishes it from other subjects. A subject can be associated with multiple principals.

User data store::
Data storage service holding principals' profiles; underlying storage can be an LDAP directory service, a relational database, or a custom `IdRepo` implementation.

Web policy agent::
Native library installed in a web server that acts as a policy agent with policies based on web page URLs.


