#!/bin/sh
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2007 Sun Microsystems Inc. All Rights Reserved
#
# The contents of this file are subject to the terms
# of the Common Development and Distribution License
# (the License). You may not use this file except in
# compliance with the License.
#
# You can obtain a copy of the License at
# https://opensso.dev.java.net/public/CDDLv1.0.html or
# opensso/legal/CDDLv1.0.txt
# See the License for the specific language governing
# permission and limitations under the License.
#
# When distributing Covered Code, include this CDDL
# Header Notice in each file and include the License file
# at opensso/legal/CDDLv1.0.txt.
# If applicable, add the following below the CDDL Header,
# with the fields enclosed by brackets [] replaced by
# your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
#
# $Id: setup,v 1.3 2008/06/25 05:41:17 qcheng Exp $
#
# Portions Copyrighted 2011 ForgeRock AS
#

AWK=`which awk`

JAVA_VER=`${JAVA_HOME}/bin/java -version 2>&1 | ${AWK} -F'"' '{print $2}'`

case $JAVA_VER in
1.0* | 1.1* | 1.2* | 1.3*)
    echo "Please include a 1.4 or newer JRE in the system PATH."
    exit 0
  ;;
esac

if [ "$1" = "-h" -o "$1" = "--help" ] ; then
  help_print=yes
fi
if [ "$1" = "-p" -o "$1" = "--path" ] ; then
  path_dest="$2"
fi

${JAVA_HOME}/bin/java -D"help.print=${help_print}" -D"path.dest=${path_dest}" -jar "lib/am_session_setup.jar"
