////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.
 
  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.
 
  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions copyright [year] [name of copyright owner]".
 
  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.
////

:figure-caption!:
:example-caption!:
:table-caption!:


[#chap-uninstall]
== Removing OpenAM Software

This chapter shows you how to uninstall OpenAM core software. See the link:../../../openam-web-policy-agents/web-users-guide/#web-users-guide[OpenAM Web Policy Agent User's Guide, window=\_blank], or the link:../../../openam-jee-policy-agents/jee-users-guide/#jee-users-guide[OpenAM Java EE Policy Agent User's Guide, window=\_blank] for instructions on removing OpenAM agents.

[#uninstall-OpenAM-core]
.To Remove OpenAM Core Software
====
After you have deployed and configured OpenAM core services, you may have as many as four locations where OpenAM files are stored on your system.

Following the steps below removes the OpenAM software and the internal configuration store. If you used an external configuration store, you can remove OpenAM configuration data after removing all the software.

. Shut down the web application container in which you deployed OpenAM.
+

[source, console]
----
$ /etc/init.d/tomcat stop
Password:
Using CATALINA_BASE:   /path/to/tomcat
Using CATALINA_HOME:   /path/to/tomcat
Using CATALINA_TMPDIR: /path/to/tomcat/temp
Using JRE_HOME:        /path/to/jdk/jre
Using CLASSPATH:       /path/to/tomcat/bin/bootstrap.jar:
 /path/to/tomcat/bin/tomcat-juli.jar
----

. Unconfigure OpenAM by removing the configuration files found in the $HOME directory of the user running the web application container.
+
A full uninstall of OpenAM core services and configuration files consists of removing the following directories:

* The configuration directory, by default `$HOME/openam`. If you did not use the default configuration location, check the value of the Base installation directory property under Deployment > Servers > __Server Name__ > General > System.

* The hidden directory that holds a file pointing to the configuration directory. For example, if you are using Apache Tomcat as the web container, this file could be `$HOME/.openamcfg/AMConfig_path_to_tomcat_webapps_openam_` OR `$HOME/.openssocfg/AMConfig_path_to_tomcat_webapps_openam_`.

+

[source, console]
----
$ rm -rf $HOME/openam $HOME/.openamcfg
----
+
Or:
+

[source, console]
----
$ rm -rf $HOME/openam $HOME/.openssocfg
----
+
If you used an external configuration store, you must remove the configuration manually from your external directory server. The default base DN for the OpenAM configuration is `dc=openam,dc=forgerock,dc=org`.
+

[NOTE]
======
At this point, you can restart the web container and configure OpenAM anew if you only want to start over with a clean configuration rather than removing OpenAM completely.
======

. Undeploy the OpenAM web application.
+
For example, if you are using Apache Tomcat as the web container, remove the `.war` file and expanded web application from the container.
+

[source, console]
----
$ cd /path/to/tomcat/webapps/
$ rm -rf openam.war openam/
----

====

