////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.
 
  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.
 
  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions copyright [year] [name of copyright owner]".
 
  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.
////

= Installation Guide
:doctype: book
:toc:
:authors: Mark Craig, David Goldsmith, Gene Hirayama, Mike Jang, Chris Lee, Vanessa Richie
:copyright: Copyright 2011-2018 ForgeRock AS.
:copyright: Portions Copyright 2024 3A Systems LLC.

:imagesdir: ../
:figure-caption!:
:example-caption!:
:table-caption!:
[abstract]
Guide showing you how to install OpenAM. OpenAM provides open source Authentication, Authorization, Entitlement and Federation software.

include::./preface.adoc[]
include::./chap-prepare-install.adoc[]
include::./chap-install-core.adoc[]
include::./chap-install-tools.adoc[]
include::./chap-install-multiple.adoc[]
include::./chap-custom-ui.adoc[]
include::./chap-cts.adoc[]
include::./chap-session-failover.adoc[]
include::./chap-uninstall.adoc[]
