#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2010-2013 ForgeRock Inc. All Rights Reserved
#
# The contents of this file are subject to the terms
# of the Common Development and Distribution License
# (the License). You may not use this file except in
# compliance with the License.
#
# You can obtain a copy of the License at
# http://forgerock.org/license/CDDLv1.0.html
# See the License for the specific language governing
# permission and limitations under the License.
#
# When distributing Covered Code, include this CDDL
# Header Notice in each file and include the License file
# at http://forgerock.org/license/CDDLv1.0.html
# If applicable, add the following below the CDDL Header,
# with the fields enclosed by brackets [] replaced by
# your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
#

## Makefile for building AMSDK and PA with Microsoft VC++ and nmake
## Use: nmake -f Makefile.nmake
##

CC = cl
LINK = link
RC = rc
MC = mc

AM_WIN32_SRC = am\source\action_decision.cpp am\source\agent_config_cache.cpp am\source\agent_configuration.cpp \
               am\source\agent_profile_service.cpp am\source\am_auth.cpp am\source\am_log.cpp am\source\am_main.cpp \
               am\source\am_map.cpp am\source\am_policy.cpp am\source\am_properties.cpp am\source\am_resource.cpp \
               am\source\am_sso.cpp am\source\am_string_set.cpp am\source\am_utils.cpp am\source\am_web.cpp \
               am\source\auth_context.cpp am\source\auth_svc.cpp am\source\base_service.cpp am\source\connection_win.cpp \
               am\source\fqdn_handler.cpp am\source\http.cpp am\source\key_value_map.cpp am\source\log.cpp \
               am\source\log_service.cpp am\source\naming_service.cpp am\source\p_cache.cpp \
               am\source\pnotify_handler.cpp am\source\policy_decision.cpp am\source\policy_engine.cpp am\source\policy_entry.cpp \
               am\source\policy_service.cpp am\source\properties.cpp am\source\ref_cnt_ptr.cpp am\source\server_info.cpp \
               am\source\service.cpp am\source\service_info.cpp am\source\session_info.cpp am\source\session_service.cpp \
               am\source\sso_entry.cpp am\source\sso_token.cpp am\source\sso_token_service.cpp am\source\string_util.cpp \
               am\source\thread_pool.cpp am\source\tree.cpp am\source\url.cpp am\source\utils.cpp am\source\xml_attribute_win.cpp \
               am\source\xml_element_win.cpp am\source\xml_tree_win.cpp 

AM_IIS6_SRC = agents\source\iis6\IisAgent6.c
AM_IIS7_SRC = agents\source\iis7\agent_main.cpp agents\source\iis7\agent_module.cpp agents\source\iis7\Iis7Agent.cpp
AM_APA_SRC = agents\source\apache\apache_agent.c
AM_APA22_SRC = agents\source\apache22\apache_agent.c
AM_APA24_SRC = agents\source\apache24\apache_agent.c
AM_PROXY4_SRC = agents\source\proxy40\web_agent.c
AM_SJSWS_SRC = agents\source\sjsws\iws_agent.c
AM_DOMINO_SRC = agents\source\domino\domino_agent.c

DEP_INCPATH = \
!IFDEF X64
   /I"extlib\WINNT\domino_64\include" /I"extlib\WINNT\proxy40\include" /I"extlib\WINNT\sjsws\include" /I"extlib\WINNT\pcre_64\include"
!ELSE
   /I"extlib\WINNT\domino\include" /I"extlib\WINNT\proxy40\include" /I"extlib\WINNT\sjsws\include" /I"extlib\WINNT\pcre\include"
!ENDIF

DEP_LIBS = kernel32.lib user32.lib ws2_32.lib winhttp.lib crypt32.lib pcre.lib advapi32.lib shlwapi.lib \
!IFDEF X64
        amsdk64.lib
!ELSE
        amsdk32.lib
!ENDIF

DEP_LIBPATH = \
!IFDEF X64
  /LIBPATH:"extlib\WINNT\domino_64\lib" \
  /LIBPATH:"extlib\WINNT\proxy40_64\lib" /LIBPATH:"extlib\WINNT\sjsws_64\lib" /LIBPATH:"extlib\WINNT\pcre_64\lib"
!ELSE
  /LIBPATH:"extlib\WINNT\domino\lib" \
  /LIBPATH:"extlib\WINNT\proxy40\lib" /LIBPATH:"extlib\WINNT\sjsws\lib" /LIBPATH:"extlib\WINNT\pcre\lib"
!ENDIF

LDFLAGS = /NOLOGO /INCREMENTAL:NO /errorReport:none \
   /MANIFEST:NO /LTCG /DYNAMICBASE /NXCOMPAT /DEBUG \
   /OPT:REF /OPT:ICF \
!IFDEF X64 
   /MACHINE:X64
!ELSE
   /MACHINE:X86
!ENDIF

LDFLAGS_LIB = /NOLOGO /ERRORREPORT:none /LTCG /NODEFAULTLIB \
!IFDEF X64 
   /MACHINE:X64
!ELSE
   /MACHINE:X86
!ENDIF

CFLAGS = /O2 /Oi /GL /Gy /D _WINDLL /FD /D_CRT_SECURE_NO_WARNINGS \
   /D AM_BUILDING_LIB /wd4996 /wd4101 /wd4244 /D WINNT \
   /EHsc /nologo /Zi /errorReport:none /Iam\source /MD /W3 /D PCRE_STATIC /c

#
# AMSDK and cryptit begin
#
.cpp.obj::
	$(CC) $(CFLAGS) $(DEP_INCPATH) /Foam\source\ $< 

crypt_util.obj	: am\source\crypt_util.c
	$(CC) $(CFLAGS) $(DEP_INCPATH) /Foam\source\crypt_util.obj am\source\crypt_util.c

notenforcedip.obj : am\source\notenforcedip.c
	$(CC) $(CFLAGS) $(DEP_INCPATH) /Foam\source\notenforcedip.obj am\source\notenforcedip.c

naming_valid.obj : am\source\naming_valid.c
	$(CC) $(CFLAGS) $(DEP_INCPATH) /Foam\source\naming_valid.obj am\source\naming_valid.c

cryptutil.obj	: am\source\crypt_util.c
	$(CC) $(CFLAGS) /MT $(DEP_INCPATH) /U _WINDLL /U AM_BUILDING_LIB /Foam\source\cryptutil.obj am\source\crypt_util.c
				
AM_WIN32_OBJECTS = $(AM_WIN32_SRC:.cpp=.obj)

amsdk.dll : crypt_util.obj notenforcedip.obj naming_valid.obj $(AM_WIN32_OBJECTS)
	$(LINK) $(LDFLAGS) $(DEP_LIBPATH) /PDB:"am\source\amsdk.pdb" \
	/DLL /OUT:"am\source\amsdk.dll" am\source\crypt_util.obj am\source\notenforcedip.obj am\source\naming_valid.obj $(AM_WIN32_OBJECTS) kernel32.lib user32.lib ws2_32.lib winhttp.lib crypt32.lib pcre.lib advapi32.lib shlwapi.lib

amsdk.lib: crypt_util.obj notenforcedip.obj naming_valid.obj $(AM_WIN32_OBJECTS)
	lib $(LDFLAGS_LIB) \
!IFDEF X64
        /OUT:"am\source\amsdk64.lib" \
!ELSE
        /OUT:"am\source\amsdk32.lib" \
!ENDIF
        am\source\crypt_util.obj am\source\notenforcedip.obj am\source\naming_valid.obj $(AM_WIN32_OBJECTS)

cryptit : cryptutil.obj
	$(LINK) $(LDFLAGS) /SUBSYSTEM:CONSOLE /OUT:"am\source\cryptit.exe" am\source\cryptutil.obj 

#
# AMSDK and cryptit end
#

#
# IIS6 and IIS7 Agent begin
#

ii6.obj : $(AM_IIS6_SRC)
	$(CC) $(CFLAGS) $(DEP_INCPATH) /DXP_WIN32 /DWINNT /Iagents\source\iis6 /Foagents\source\iis6\ $(AM_IIS6_SRC)

iis6i : ii6.obj
	$(LINK) $(LDFLAGS) $(DEP_LIBPATH) /EXPORT:GetExtensionVersion /EXPORT:HttpExtensionProc /EXPORT:TerminateExtension \
		/PDB:"agents\source\iis6\amiis6.pdb" \
		/DLL /OUT:"agents\source\iis6\amiis6.dll" agents\source\iis6\IisAgent6.obj /LIBPATH:"am\source" $(DEP_LIBS)


iis7.obj : $(AM_IIS7_SRC)
        $(MC) -A -b -c -h agents\source\iis7\ -r agents\source\iis7\ agents\source\iis7\agent_ev.mc
	$(CC) /I"C:\Program Files\Microsoft SDKs\Windows\v7.1\Include" $(CFLAGS) $(DEP_INCPATH) /D WIN32 /Iagents\source\iis7 /Foagents\source\iis7\ $(AM_IIS7_SRC)

iis7i	: iis7.obj
	$(RC) /nologo /fo agents\source\iis7\agent_ev.res agents\source\iis7\agent_ev.rc
	$(LINK) $(LDFLAGS) $(DEP_LIBPATH) /EXPORT:RegisterModule \
	/PDB:"agents\source\iis7\amiis7module.pdb" \
	/DLL /OUT:"agents\source\iis7\amiis7module.dll" agents\source\iis7\agent_main.obj agents\source\iis7\agent_module.obj \
        agents\source\iis7\Iis7Agent.obj agents\source\iis7\agent_ev.res /LIBPATH:"am\source" $(DEP_LIBS)

#
# IIS6 and IIS7 Agent end
#

#
# Apache 2 and 2.2 Agent begin
#

apache.obj : $(AM_APA_SRC)
	$(CC) $(CFLAGS) /I"extlib\WINNT\apache\include" $(DEP_INCPATH) /DWIN32 /DAPACHE2 /DEAPI /DUSE_EXPAT /DCORE_PRIVATE /DXP_WIN32 /Iagents\source\apache /Foagents\source\apache\ /Tc $(AM_APA_SRC)

apachei : apache.obj
	$(LINK) $(LDFLAGS) /LIBPATH:"extlib\WINNT\apache\lib" $(DEP_LIBPATH) /DEF:"agents\source\apache\libamapc.def" \
		/PDB:"agents\source\apache\libamapc2.pdb" \
		/DLL /OUT:agents\source\apache\libamapc2.dll agents\source\apache\apache_agent.obj /LIBPATH:"am\source" $(DEP_LIBS) libapr.lib libapriconv.lib libhttpd.lib

apache22.obj : $(AM_APA22_SRC)
	$(CC) $(CFLAGS) /I"extlib\WINNT\apache22\include" $(DEP_INCPATH) /DWIN32 /DAPACHE2 /DEAPI /DUSE_EXPAT /DCORE_PRIVATE /DXP_WIN32 /Iagents\source\apache22 /Foagents\source\apache22\ /Tc $(AM_APA22_SRC)

apache2i : apache22.obj
	$(LINK) $(LDFLAGS) /LIBPATH:"extlib\WINNT\apache22\lib" $(DEP_LIBPATH) /EXPORT:dsame_module \
		/PDB:"agents\source\apache22\libamapc22.pdb" \
		/DLL /OUT:agents\source\apache22\libamapc22.dll /LIBPATH:"extlib\WINNT\apache2\lib" agents\source\apache22\apache_agent.obj /LIBPATH:"am\source" $(DEP_LIBS) libapr-1.lib libaprutil-1.lib libhttpd.lib

apache24.obj : $(AM_APA24_SRC)
	$(CC) $(CFLAGS) /I"extlib\WINNT\apache24\include" $(DEP_INCPATH) /DWIN32 /DAPACHE2 /DEAPI /DUSE_EXPAT /DCORE_PRIVATE /DXP_WIN32 /Iagents\source\apache24 /Foagents\source\apache24\ /Tc $(AM_APA24_SRC)

apache24i : apache24.obj
	$(LINK) $(LDFLAGS) /LIBPATH:"extlib\WINNT\apache24\lib" $(DEP_LIBPATH) /EXPORT:dsame_module \
		/PDB:"agents\source\apache24\libamapc24.pdb" \
		/DLL /OUT:agents\source\apache24\libamapc24.dll /LIBPATH:"extlib\WINNT\apache24\lib" agents\source\apache24\apache_agent.obj /LIBPATH:"am\source" $(DEP_LIBS) libapr-1.lib libaprutil-1.lib libhttpd.lib


#
# Apache 2 and 2.2 Agent end
#

#
# Proxy40 Agent begin
#
proxy40.obj : $(AM_PROXY4_SRC)
	$(CC) $(CFLAGS) $(DEP_INCPATH) /DXP_WIN32 /DWINNT /Iagents\source\proxy40 /Foagents\source\proxy40\ $(AM_PROXY4_SRC)

proxy40i	: proxy40.obj 
	$(LINK) $(LDFLAGS) $(DEP_LIBPATH) /DEF:"agents\source\proxy40\proxy4agent.def" \
		/PDB:"agents\source\proxy40\ampxy4.pdb" \
		/DLL /OUT:agents\source\proxy40\ampxy4.dll agents\source\proxy40\web_agent.obj /LIBPATH:"am\source" $(DEP_LIBS) ns-httpd40.lib
#
# Proxy40 Agent end
#

#
# SJSWS Agent begin
#
sjsws.obj : $(AM_SJSWS_SRC)
	$(CC) $(CFLAGS) $(DEP_INCPATH) /DXP_WIN32 /DWINNT /Iagents\source\sjsws /Foagents\source\sjsws\ $(AM_SJSWS_SRC)

sjswsi	: sjsws.obj 
	$(LINK) $(LDFLAGS) $(DEP_LIBPATH) /DEF:"agents\source\sjsws\iws_agent.def" \
		/PDB:"agents\source\sjsws\ames6.pdb" \
		/DLL /OUT:agents\source\sjsws\ames6.dll agents\source\sjsws\iws_agent.obj /LIBPATH:"am\source" $(DEP_LIBS) ns-httpd40.lib
#
# SJSWS Agent end
#

#
# Domino Agent begin
#
domino.obj : $(AM_DOMINO_SRC)
	$(CC) $(CFLAGS) $(DEP_INCPATH) /D W32 /D WIN32 /D XP_WIN32 /D _WINDOWS /D _REENTRANT /D USE_THREADSAFE_INTERFACES /Iagents\source\domino /Foagents\source\domino\ $(AM_DOMINO_SRC)

dominoi	: domino.obj 
	$(LINK) $(LDFLAGS) $(DEP_LIBPATH) /DEF:"agents\source\domino\amdomino.def" \
		/PDB:"agents\source\domino\amdomino.pdb" \
		/DLL /OUT:agents\source\domino\amdomino.dll agents\source\domino\domino_agent.obj /LIBPATH:"am\source" $(DEP_LIBS) notes.lib ws2_32.lib

#
# Domino Agent end
#

all: amsdk.lib cryptit iis6i iis7i apachei apache2i apache24i proxy40i sjswsi dominoi
sdk: amsdk.dll cryptit
iis6: amsdk.lib cryptit iis6i
iis7: amsdk.lib cryptit iis7i
apache: amsdk.lib cryptit apachei
apache22: amsdk.lib cryptit apache2i
apache24: amsdk.lib cryptit apache24i
proxy40: amsdk.lib cryptit proxy40i
sjsws: amsdk.lib cryptit sjswsi
domino: amsdk.lib cryptit dominoi
