/*
 * The contents of this file are subject to the terms of the Common Development and
 * Distribution License (the License). You may not use this file except in compliance with the
 * License.
 *
 * You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
 * specific language governing permission and limitations under the License.
 *
 * When distributing Covered Software, include this CDDL Header Notice in each file and include
 * the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
 * Header, with the fields enclosed by brackets [] replaced by your own identifying
 * information: "Portions copyright [year] [name of copyright owner]".
 *
 * Copyright 2015 ForgeRock AS.
 */

package org.forgerock.openam.core.rest.record;

/**
 * Record constants
 */
public class RecordConstants {

    // REST endpoint
    public static final String RECORD_REST_ENDPOINT = "records";

    // REST Action
    public static final String START_ACTION = "start";
    public static final String STATUS_ACTION = "status";
    public static final String STOP_ACTION = "stop";

    // Debugger
    public static final String DEBUG_INSTANCE_NAME = "amRecord";

    // Folders generated by the record
    public static final String RECORD_FOLDER_NAME = "record";
    public static final String THREAD_DUMP_FOLDER_NAME = "threadDump";
    public static final String DEBUG_FOLDER_NAME = "debug";

    // File names generated by the record
    public static final String INFO_FILE_NAME = "info.json";
    public static final String HISTORY_FILE_NAME = "RecordsHistory.txt";
    public static final String TREADS_DUMP_FILE_NAME = "threadDump_$DATE$.txt";
    public static final String OPENAM_CONFIG_EXPORT_FILE_NAME = "OpenamConfigExport_$DATE$.xml";

    //All JSON Labels

    // Global
    public static final String ISSUE_ID_LABEL = "issueID";
    public static final String REFERENCE_ID_LABEL = "referenceID";
    public static final String DESCRIPTION_LABEL = "description";
    public static final String ZIP_ENABLE_LABEL = "zipEnable";

    // ThreadDump
    public static final String THREAD_DUMP_LABEL = "threadDump";
    public static final String THREAD_DUMP_ENABLE_LABEL = "enable";
    public static final String THREAD_DUMP_DELAY_LABEL = "delay";
    public static final String THREAD_DUMP_DELAY_TIME_UNIT_LABEL = "timeUnit";
    public static final String THREAD_DUMP_DELAY_VALUE_LABEL = "value";

    // Config Export
    public static final String CONFIG_EXPORT_LABEL = "configExport";
    public static final String CONFIG_EXPORT_ENABLE_LABEL = "enable";
    public static final String CONFIG_EXPORT_PASSWORD_LABEL = "password";
    public static final String CONFIG_EXPORT_SHARE_PASSWORD_LABEL = "sharePassword";

    // Debug logs
    public static final String DEBUG_LOGS_LABEL = "debugLogs";
    public static final String DEBUG_LOGS_DEBUG_LEVEL_LABEL = "debugLevel";
    public static final String DEBUG_LOGS_AUTOSTOP_LABEL = "autoStop";
    public static final String DEBUG_LOGS_AUTOSTOP_TIME_LABEL = "time";
    public static final String DEBUG_LOGS_AUTOSTOP_TIME_UNIT_LABEL = "timeUnit";
    public static final String DEBUG_LOGS_AUTOSTOP_TIME_VALUE_LABEL = "value";
    public static final String DEBUG_LOGS_AUTOSTOP_FILESIZE_LABEL = "fileSize";
    public static final String DEBUG_LOGS_AUTOSTOP_FILESIZE_SIZEUNIT_LABEL = "sizeUnit";
    public static final String DEBUG_LOGS_AUTOSTOP_FILESIZE_VALUE_LABEL = "value";
}
