/**
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2009 Sun Microsystems Inc. All Rights Reserved
 *
 * The contents of this file are subject to the terms
 * of the Common Development and Distribution License
 * (the License). You may not use this file except in
 * compliance with the License.
 *
 * You can obtain a copy of the License at
 * https://opensso.dev.java.net/public/CDDLv1.0.html or
 * opensso/legal/CDDLv1.0.txt
 * See the License for the specific language governing
 * permission and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL
 * Header Notice in each file and include the License file
 * at opensso/legal/CDDLv1.0.txt.
 * If applicable, add the following below the CDDL Header,
 * with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * $Id: SUN_OPENSSO_SERVER_MIB.java,v 1.2 2009/10/20 23:53:12 bigfatrat Exp $
 *
 */

package com.sun.identity.monitoring;

import java.io.Serializable;
import java.util.Hashtable;
import javax.management.MBeanServer;
import javax.management.ObjectName;
import javax.management.InstanceAlreadyExistsException;
import com.sun.management.snmp.agent.SnmpMib;
import com.sun.management.snmp.agent.SnmpMibTable;
import com.sun.management.snmp.agent.SnmpStandardObjectServer;

/**
 * The class is used for representing "SUN-OPENSSO-SERVER-MIB".
 * You can edit the file if you want to modify the behavior of the MIB.
 */
public class SUN_OPENSSO_SERVER_MIB extends SnmpMib implements Serializable {

    private Object instanceGroup;
    private Object authSvcGroup;
    private Object sessSvcGroup;
    private Object loggingSvcGroup;
    private Object policySvcGroup;
    private Object idrepoSvcGroup;
    private Object svcmgmtSvcGroup;
    private Object saml1SvcGroup;
    private Object saml2SvcGroup;
    private Object idffSvcGroup;
    private Object topologyGroup;
    private Object wssAgentsGroup;
    private Object fedCotsGroup;
    private Object policyAgentsGroup;
    private Object fedEntitiesGroup;
    private Object entitlementsGroup;

    /*
     * this "prefix" is generated by mibgen; if another mibgen is done,
     * whereever "srvPrfx" is used would be changed.
     */
    String srvPrfx = "_SsoServerInstance:name=com.sun.identity.monitoring.";

    /**
     * Default constructor. Initialize the Mib tree.
     */
    public SUN_OPENSSO_SERVER_MIB() {
        mibName = "SUN_OPENSSO_SERVER_MIB";
    }

    /**
     * Initialization of the MIB with no registration in Java DMK.
     */
    public void init() throws IllegalAccessException {
        // Allow only one initialization of the MIB.
        //
        if (isInitialized == true) {
            return ;
        }

        try  {
            populate(null, null);
        } catch(IllegalAccessException x)  {
            throw x;
        } catch(RuntimeException x)  {
            throw x;
        } catch(Exception x)  {
            throw new Error(x.getMessage());
        }

        isInitialized = true;
    }

    /**
     * Initialization of the MIB with AUTOMATIC REGISTRATION in Java DMK.
     */
    public ObjectName preRegister(MBeanServer server, ObjectName name)
            throws Exception {
        // Allow only one initialization of the MIB.
        //
        if (isInitialized == true) {
            throw new InstanceAlreadyExistsException();
        }

        // Initialize MBeanServer information.
        //
        this.server = server;

        populate(server, name);

        isInitialized = true;
        return name;
    }

    /**
     * Initialization of the MIB with no registration in Java DMK.
     */
    public void populate(MBeanServer server, ObjectName name) 
        throws Exception {
        // Allow only one initialization of the MIB.
        //
        if (isInitialized == true) {
            return ;
        }

        if (objectserver == null) 
            objectserver = new SnmpStandardObjectServer();

        // Initialization of the "SsoServerInstance" group.
        // To disable support of this group, redefine the 
        // "createSsoServerInstanceMetaNode()" factory method, and make it
        // return "null"
        //
        initSsoServerInstance(server);

        // Initialization of the "SsoServerFedEntities" group.
        // To disable support of this group, redefine the 
        // "createSsoServerFedEntitiesMetaNode()" factory method, and make it
        // return "null"
        //
        initSsoServerFedEntities(server);

        // Initialization of the "SsoServerFedCOTs" group.
        // To disable support of this group, redefine the 
        // "createSsoServerFedCOTsMetaNode()" factory method, and make it
        // return "null"
        //
        initSsoServerFedCOTs(server);

        // Initialization of the "SsoServerSAML2Svc" group.
        // To disable support of this group, redefine the 
        // "createSsoServerSAML2SvcMetaNode()" factory method, and make it
        // return "null"
        //
        initSsoServerSAML2Svc(server);

        // Initialization of the "SsoServerSAML1Svc" group.
        // To disable support of this group, redefine the 
        // "createSsoServerSAML1SvcMetaNode()" factory method, and make it
        // return "null"
        //
        initSsoServerSAML1Svc(server);

        // Initialization of the "SsoServerIdRepoSvc" group.
        // To disable support of this group, redefine the 
        // "createSsoServerIdRepoSvcMetaNode()" factory method, and make it
        // return "null"
        //
        initSsoServerIdRepoSvc(server);

        // Initialization of the "SsoServerSvcMgmtSvc" group.
        // To disable support of this group, redefine the 
        // "createSsoServerSvcMgmtSvcMetaNode()" factory method, and make it
        // return "null"
        //
        initSsoServerSvcMgmtSvc(server);

        // Initialization of the "SsoServerPolicySvc" group.
        // To disable support of this group, redefine the 
        // "createSsoServerPolicySvcMetaNode()" factory method, and make it
        // return "null"
        //
        initSsoServerPolicySvc(server);

        // Initialization of the "SsoServerLoggingSvc" group.
        // To disable support of this group, redefine the 
        // "createSsoServerLoggingSvcMetaNode()" factory method, and make it
        // return "null"
        //
        initSsoServerLoggingSvc(server);

        // Initialization of the "SsoServerSessSvc" group.
        // To disable support of this group, redefine the 
        // "createSsoServerSessSvcMetaNode()" factory method, and make it
        // return "null"
        //
        initSsoServerSessSvc(server);

        // Initialization of the "SsoServerAuthSvc" group.
        // To disable support of this group, redefine the 
        // "createSsoServerAuthSvcMetaNode()" factory method, and make it
        // return "null"
        //
        initSsoServerAuthSvc(server);

        // Initialization of the "SsoServerTopology" group.
        // To disable support of this group, redefine the 
        // "createSsoServerTopologyMetaNode()" factory method, and make it
        // return "null"
        //
        initSsoServerTopology(server);

        // Initialization of the "SsoServerEntitlementSvc" group.
        // To disable support of this group, redefine the 
        // "createSsoServerEntitlementSvcMetaNode()" factory method, and make
        // it return "null"
        //
        initSsoServerEntitlementSvc(server);

        // Initialization of the "SsoServerWSSAgents" group.
        // To disable support of this group, redefine the 
        // "createSsoServerWSSAgentsMetaNode()" factory method, and make it
        // return "null"
        //
        initSsoServerWSSAgents(server);

        // Initialization of the "SsoServerPolicyAgents" group.
        // To disable support of this group, redefine the 
        // "createSsoServerPolicyAgentsMetaNode()" factory method, and make it
        // return "null"
        //
        initSsoServerPolicyAgents(server);

        // Initialization of the "SsoServerIDFFSvc" group.
        // To disable support of this group, redefine the 
        // "createSsoServerIDFFSvcMetaNode()" factory method, and make it
        // return "null"
        //
        initSsoServerIDFFSvc(server);

        isInitialized = true;
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "SsoServerInstance" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "SsoServerInstance" group.
     * 
     * To disable support of this group, redefine the 
     * "createSsoServerInstanceMetaNode()" factory method, and make it
     // return "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initSsoServerInstance(MBeanServer server) 
        throws Exception {
        final String oid =
            getGroupOid("SsoServerInstance", "1.3.6.1.4.1.42.2.230.3.1.1.2.1");
        ObjectName objname = null;
        if (server != null) {
            objname = getGroupObjectName(
                "SsoServerInstance",
                oid,
                mibName + 
                    ":name=com.sun.identity.monitoring.SsoServerInstance");
        }
        final SsoServerInstanceMeta meta =
            createSsoServerInstanceMetaNode(
                "SsoServerInstance",
                    oid,
                    objname,
                    server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the "SsoServerInstanceMBean"
            // interface.
            //
            instanceGroup =
                (SsoServerInstanceMBean)createSsoServerInstanceMBean(
                    "SsoServerInstance", oid, objname, server);
            meta.setInstance ((SsoServerInstanceMBean)instanceGroup);
            registerGroupNode("SsoServerInstance", oid, objname, meta,
                instanceGroup, server);
        }
    }


    /**
     * Factory method for "SsoServerInstance" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerInstance")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "SsoServerInstance" group (SsoServerInstanceMeta)
     * 
     **/
    protected SsoServerInstanceMeta createSsoServerInstanceMetaNode(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        return new SsoServerInstanceMeta(this, objectserver);
    }


    /**
     * Factory method for "SsoServerInstance" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerInstance")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "SsoServerInstance" group (SsoServerInstance)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "SsoServerInstanceMBean"
     * interface.
     **/
    protected Object createSsoServerInstanceMBean(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        // Note that when using standard metadata,
        // the returned object must implement the "SsoServerInstanceMBean"
        // interface.
        //
        if (server != null) 
            return new SsoServerInstanceImpl(this,server);
        else 
            return new SsoServerInstanceImpl(this);
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "SsoServerFedEntities" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "SsoServerFedEntities" group.
     * 
     * To disable support of this group, redefine the 
     * "createSsoServerFedEntitiesMetaNode()" factory method, and make it
     * return "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initSsoServerFedEntities(MBeanServer server) 
        throws Exception {
        final String oid =
            getGroupOid(
                "SsoServerFedEntities", "1.3.6.1.4.1.42.2.230.3.1.1.2.1.19");
        ObjectName objname = null;
        if (server != null) {
            objname =
                getGroupObjectName("SsoServerFedEntities",
                    oid, mibName + srvPrfx + "SsoServerFedEntities");
        }
        final SsoServerFedEntitiesMeta meta =
            createSsoServerFedEntitiesMetaNode(
                "SsoServerFedEntities",
                oid,
                objname,
                server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the 
            // "SsoServerFedEntitiesMBean"
            // interface.
            //
            fedEntitiesGroup =
                (SsoServerFedEntitiesMBean) createSsoServerFedEntitiesMBean(
                    "SsoServerFedEntities", oid, objname, server);
            meta.setInstance ((SsoServerFedEntitiesMBean)fedEntitiesGroup);
            registerGroupNode("SsoServerFedEntities", oid, objname, meta,
                fedEntitiesGroup, server);
        }
    }


    /**
     * Factory method for "SsoServerFedEntities" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerFedEntities")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "SsoServerFedEntities" group (SsoServerFedEntitiesMeta)
     * 
     **/
    protected SsoServerFedEntitiesMeta createSsoServerFedEntitiesMetaNode(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        return new SsoServerFedEntitiesMeta(this, objectserver);
    }


    /**
     * Factory method for "SsoServerFedEntities" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerFedEntities")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "SsoServerFedEntities" group (SsoServerFedEntities)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "SsoServerFedEntitiesMBean"
     * interface.
     **/
    protected Object createSsoServerFedEntitiesMBean(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {

        // Note that when using standard metadata,
        // the returned object must implement the "SsoServerFedEntitiesMBean"
        // interface.
        //
        if (server != null) 
            return new SsoServerFedEntitiesImpl(this,server);
        else 
            return new SsoServerFedEntitiesImpl(this);
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "SsoServerFedCOTs" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "SsoServerFedCOTs" group.
     * 
     * To disable support of this group, redefine the 
     * "createSsoServerFedCOTsMetaNode()" factory method, and make it return
     * "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initSsoServerFedCOTs(MBeanServer server) 
        throws Exception {
        final String oid =
            getGroupOid(
                "SsoServerFedCOTs", "1.3.6.1.4.1.42.2.230.3.1.1.2.1.18");
        ObjectName objname = null;
        if (server != null) {
            objname =
                getGroupObjectName("SsoServerFedCOTs",
                    oid, mibName + srvPrfx + "SsoServerFedCOTs");
        }
        final SsoServerFedCOTsMeta meta = createSsoServerFedCOTsMetaNode(
            "SsoServerFedCOTs", oid, objname, server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the "SsoServerFedCOTsMBean"
            // interface.
            //
            fedCotsGroup =
                (SsoServerFedCOTsMBean) createSsoServerFedCOTsMBean(
                    "SsoServerFedCOTs", oid, objname, server);
            meta.setInstance ((SsoServerFedCOTsMBean)fedCotsGroup);
            registerGroupNode("SsoServerFedCOTs", oid, objname, meta,
                fedCotsGroup, server);
        }
    }


    /**
     * Factory method for "SsoServerFedCOTs" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerFedCOTs")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "SsoServerFedCOTs" group (SsoServerFedCOTsMeta)
     * 
     **/
    protected SsoServerFedCOTsMeta createSsoServerFedCOTsMetaNode(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        return new SsoServerFedCOTsMeta(this, objectserver);
    }


    /**
     * Factory method for "SsoServerFedCOTs" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerFedCOTs")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "SsoServerFedCOTs" group (SsoServerFedCOTs)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "SsoServerFedCOTsMBean"
     * interface.
     **/
    protected Object createSsoServerFedCOTsMBean(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {

        // Note that when using standard metadata,
        // the returned object must implement the "SsoServerFedCOTsMBean"
        // interface.
        //
        if (server != null) 
            return new SsoServerFedCOTsImpl(this,server);
        else 
            return new SsoServerFedCOTsImpl(this);
    }
    // ------------------------------------------------------------
    // 
    // Initialization of the "SsoServerSAML2Svc" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "SsoServerSAML2Svc" group.
     * 
     * To disable support of this group, redefine the 
     * "createSsoServerSAML2SvcMetaNode()" factory method, and make it return
     * "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initSsoServerSAML2Svc(MBeanServer server) 
        throws Exception {
        final String oid =
            getGroupOid(
                "SsoServerSAML2Svc",
                "1.3.6.1.4.1.42.2.230.3.1.1.2.1.17");
        ObjectName objname = null;
        if (server != null) {
            objname =
                getGroupObjectName(
                    "SsoServerSAML2Svc",
                    oid, mibName + srvPrfx + "SsoServerSAML2Svc");
        }
        final SsoServerSAML2SvcMeta meta =
            createSsoServerSAML2SvcMetaNode(
                "SsoServerSAML2Svc", oid, objname, server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the "SsoServerSAML2SvcMBean"
            // interface.
            //
            saml2SvcGroup =
                (SsoServerSAML2SvcMBean) createSsoServerSAML2SvcMBean(
                    "SsoServerSAML2Svc", oid, objname, server);
            meta.setInstance ((SsoServerSAML2SvcMBean)saml2SvcGroup);
            registerGroupNode("SsoServerSAML2Svc", oid, objname, meta,
                saml2SvcGroup, server);
        }
    }


    /**
     * Factory method for "SsoServerSAML2Svc" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerSAML2Svc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "SsoServerSAML2Svc" group (SsoServerSAML2SvcMeta)
     * 
     **/
    protected SsoServerSAML2SvcMeta createSsoServerSAML2SvcMetaNode(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        return new SsoServerSAML2SvcMeta(this, objectserver);
    }


    /**
     * Factory method for "SsoServerSAML2Svc" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerSAML2Svc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "SsoServerSAML2Svc" group (SsoServerSAML2Svc)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "SsoServerSAML2SvcMBean"
     * interface.
     **/
    protected Object createSsoServerSAML2SvcMBean(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {

        // Note that when using standard metadata,
        // the returned object must implement the "SsoServerSAML2SvcMBean"
        // interface.
        //
        if (server != null) 
            return new SsoServerSAML2SvcImpl(this,server);
        else 
            return new SsoServerSAML2SvcImpl(this);
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "SsoServerSAML1Svc" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "SsoServerSAML1Svc" group.
     * 
     * To disable support of this group, redefine the 
     * "createSsoServerSAML1SvcMetaNode()" factory method, and make it return
     * "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initSsoServerSAML1Svc(MBeanServer server) 
        throws Exception {
        final String oid =
            getGroupOid(
                "SsoServerSAML1Svc", "1.3.6.1.4.1.42.2.230.3.1.1.2.1.16");
        ObjectName objname = null;
        if (server != null) {
            objname = getGroupObjectName("SsoServerSAML1Svc",
                oid, mibName + srvPrfx + "SsoServerSAML1Svc");
        }
        final SsoServerSAML1SvcMeta meta =
            createSsoServerSAML1SvcMetaNode(
                "SsoServerSAML1Svc", oid, objname, server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the "SsoServerSAML1SvcMBean"
            // interface.
            //
            saml1SvcGroup =
                (SsoServerSAML1SvcMBean)createSsoServerSAML1SvcMBean(
                    "SsoServerSAML1Svc", oid, objname, server);
            meta.setInstance ((SsoServerSAML1SvcMBean)saml1SvcGroup);
            registerGroupNode("SsoServerSAML1Svc", oid, objname, meta,
                saml1SvcGroup, server);
        }
    }


    /**
     * Factory method for "SsoServerSAML1Svc" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerSAML1Svc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "SsoServerSAML1Svc" group (SsoServerSAML1SvcMeta)
     * 
     **/
    protected SsoServerSAML1SvcMeta createSsoServerSAML1SvcMetaNode(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        return new SsoServerSAML1SvcMeta(this, objectserver);
    }


    /**
     * Factory method for "SsoServerSAML1Svc" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerSAML1Svc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "SsoServerSAML1Svc" group (SsoServerSAML1Svc)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "SsoServerSAML1SvcMBean"
     * interface.
     **/
    protected Object createSsoServerSAML1SvcMBean(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {

        // Note that when using standard metadata,
        // the returned object must implement the "SsoServerSAML1SvcMBean"
        // interface.
        //
        if (server != null) 
            return new SsoServerSAML1SvcImpl(this,server);
        else 
            return new SsoServerSAML1SvcImpl(this);
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "SsoServerIdRepoSvc" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "SsoServerIdRepoSvc" group.
     * 
     * To disable support of this group, redefine the 
     * "createSsoServerIdRepoSvcMetaNode()" factory method, and make it
     * return "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initSsoServerIdRepoSvc(MBeanServer server) 
        throws Exception {
        final String oid =
            getGroupOid(
                "SsoServerIdRepoSvc", "1.3.6.1.4.1.42.2.230.3.1.1.2.1.15");
        ObjectName objname = null;
        if (server != null) {
            objname = getGroupObjectName("SsoServerIdRepoSvc",
                oid, mibName + srvPrfx + "SsoServerIdRepoSvc");
        }
        final SsoServerIdRepoSvcMeta meta =
            createSsoServerIdRepoSvcMetaNode(
                "SsoServerIdRepoSvc",
                oid,
                objname,
                server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the "SsoServerIdRepoSvcMBean"
            // interface.
            //
            idrepoSvcGroup =
                (SsoServerIdRepoSvcMBean) createSsoServerIdRepoSvcMBean(
                    "SsoServerIdRepoSvc", oid, objname, server);
            meta.setInstance ((SsoServerIdRepoSvcMBean)idrepoSvcGroup);
            registerGroupNode("SsoServerIdRepoSvc", oid, objname, meta,
                idrepoSvcGroup, server);
        }
    }


    /**
     * Factory method for "SsoServerIdRepoSvc" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerIdRepoSvc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "SsoServerIdRepoSvc" group (SsoServerIdRepoSvcMeta)
     * 
     **/
    protected SsoServerIdRepoSvcMeta createSsoServerIdRepoSvcMetaNode(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        return new SsoServerIdRepoSvcMeta(this, objectserver);
    }


    /**
     * Factory method for "SsoServerIdRepoSvc" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerIdRepoSvc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "SsoServerIdRepoSvc" group (SsoServerIdRepoSvc)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "SsoServerIdRepoSvcMBean"
     * interface.
     **/
    protected Object createSsoServerIdRepoSvcMBean(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {

        // Note that when using standard metadata,
        // the returned object must implement the "SsoServerIdRepoSvcMBean"
        // interface.
        //
        if (server != null) 
            return new SsoServerIdRepoSvcImpl(this,server);
        else 
            return new SsoServerIdRepoSvcImpl(this);
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "SsoServerSvcMgmtSvc" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "SsoServerSvcMgmtSvc" group.
     * 
     * To disable support of this group, redefine the 
     * "createSsoServerSvcMgmtSvcMetaNode()" factory method, and make it
     * return "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initSsoServerSvcMgmtSvc(MBeanServer server) 
        throws Exception {
        final String oid =
            getGroupOid(
                "SsoServerSvcMgmtSvc", "1.3.6.1.4.1.42.2.230.3.1.1.2.1.14");
        ObjectName objname = null;
        if (server != null) {
            objname =
                getGroupObjectName("SsoServerSvcMgmtSvc",
                    oid, mibName + srvPrfx + "SsoServerSvcMgmtSvc");
        }
        final SsoServerSvcMgmtSvcMeta meta =
            createSsoServerSvcMgmtSvcMetaNode(
                "SsoServerSvcMgmtSvc", oid, objname, server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the "SsoServerSvcMgmtSvcMBean"
            // interface.
            //
            svcmgmtSvcGroup =
                (SsoServerSvcMgmtSvcMBean) createSsoServerSvcMgmtSvcMBean(
                    "SsoServerSvcMgmtSvc", oid, objname, server);
            meta.setInstance ((SsoServerSvcMgmtSvcMBean)svcmgmtSvcGroup);
            registerGroupNode("SsoServerSvcMgmtSvc", oid, objname, meta,
                svcmgmtSvcGroup, server);
        }
    }


    /**
     * Factory method for "SsoServerSvcMgmtSvc" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerSvcMgmtSvc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "SsoServerSvcMgmtSvc" group (SsoServerSvcMgmtSvcMeta)
     * 
     **/
    protected SsoServerSvcMgmtSvcMeta createSsoServerSvcMgmtSvcMetaNode(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        return new SsoServerSvcMgmtSvcMeta(this, objectserver);
    }


    /**
     * Factory method for "SsoServerSvcMgmtSvc" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerSvcMgmtSvc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "SsoServerSvcMgmtSvc" group (SsoServerSvcMgmtSvc)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "SsoServerSvcMgmtSvcMBean"
     * interface.
     **/
    protected Object createSsoServerSvcMgmtSvcMBean(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {

        // Note that when using standard metadata,
        // the returned object must implement the "SsoServerSvcMgmtSvcMBean"
        // interface.
        //
        if (server != null) 
            return new SsoServerSvcMgmtSvcImpl(this,server);
        else 
            return new SsoServerSvcMgmtSvcImpl(this);
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "SsoServerPolicySvc" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "SsoServerPolicySvc" group.
     * 
     * To disable support of this group, redefine the 
     * "createSsoServerPolicySvcMetaNode()" factory method, and make it
     * return "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initSsoServerPolicySvc(MBeanServer server) 
        throws Exception {
        final String oid = 
            getGroupOid(
                "SsoServerPolicySvc", "1.3.6.1.4.1.42.2.230.3.1.1.2.1.13");
        ObjectName objname = null;
        if (server != null) {
            objname =
                getGroupObjectName("SsoServerPolicySvc",
                    oid, mibName + srvPrfx + "SsoServerPolicySvc");
        }
        final SsoServerPolicySvcMeta meta =
             createSsoServerPolicySvcMetaNode(
                 "SsoServerPolicySvc", oid, objname, server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the "SsoServerPolicySvcMBean"
            // interface.
            //
            policySvcGroup =
                (SsoServerPolicySvcMBean)createSsoServerPolicySvcMBean(
                    "SsoServerPolicySvc", oid, objname, server);
            meta.setInstance ((SsoServerPolicySvcMBean)policySvcGroup);
            registerGroupNode("SsoServerPolicySvc", oid, objname, meta,
                policySvcGroup, server);
        }
    }


    /**
     * Factory method for "SsoServerPolicySvc" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerPolicySvc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "SsoServerPolicySvc" group (SsoServerPolicySvcMeta)
     * 
     **/
    protected SsoServerPolicySvcMeta createSsoServerPolicySvcMetaNode(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        return new SsoServerPolicySvcMeta(this, objectserver);
    }


    /**
     * Factory method for "SsoServerPolicySvc" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerPolicySvc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "SsoServerPolicySvc" group (SsoServerPolicySvc)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "SsoServerPolicySvcMBean"
     * interface.
     **/
    protected Object createSsoServerPolicySvcMBean(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {

        // Note that when using standard metadata,
        // the returned object must implement the "SsoServerPolicySvcMBean"
        // interface.
        //
        if (server != null) 
            return new SsoServerPolicySvcImpl(this,server);
        else 
            return new SsoServerPolicySvcImpl(this);
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "SsoServerLoggingSvc" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "SsoServerLoggingSvc" group.
     * 
     * To disable support of this group, redefine the 
     * "createSsoServerLoggingSvcMetaNode()" factory method, and make it
     * return "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initSsoServerLoggingSvc(MBeanServer server) 
        throws Exception {
        final String oid =
            getGroupOid(
                "SsoServerLoggingSvc", "1.3.6.1.4.1.42.2.230.3.1.1.2.1.12");
        ObjectName objname = null;
        if (server != null) {
            objname =
                getGroupObjectName("SsoServerLoggingSvc",
                    oid, mibName + srvPrfx + "SsoServerLoggingSvc");
        }
        final SsoServerLoggingSvcMeta meta =
            createSsoServerLoggingSvcMetaNode(
                "SsoServerLoggingSvc", oid, objname, server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the "SsoServerLoggingSvcMBean"
            // interface.
            //
            loggingSvcGroup =
                (SsoServerLoggingSvcMBean) createSsoServerLoggingSvcMBean(
                    "SsoServerLoggingSvc", oid, objname, server);
            meta.setInstance ((SsoServerLoggingSvcMBean)loggingSvcGroup);
            registerGroupNode("SsoServerLoggingSvc", oid, objname, meta,
                loggingSvcGroup, server);
        }
    }


    /**
     * Factory method for "SsoServerLoggingSvc" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerLoggingSvc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "SsoServerLoggingSvc" group (SsoServerLoggingSvcMeta)
     * 
     **/
    protected SsoServerLoggingSvcMeta createSsoServerLoggingSvcMetaNode(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        return new SsoServerLoggingSvcMeta(this, objectserver);
    }


    /**
     * Factory method for "SsoServerLoggingSvc" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerLoggingSvc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "SsoServerLoggingSvc" group (SsoServerLoggingSvc)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "SsoServerLoggingSvcMBean"
     * interface.
     **/
    protected Object createSsoServerLoggingSvcMBean(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {

        // Note that when using standard metadata,
        // the returned object must implement the "SsoServerLoggingSvcMBean"
        // interface.
        //
        if (server != null) 
            return new SsoServerLoggingSvcImpl(this,server);
        else 
            return new SsoServerLoggingSvcImpl(this);
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "SsoServerSessSvc" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "SsoServerSessSvc" group.
     * 
     * To disable support of this group, redefine the 
     * "createSsoServerSessSvcMetaNode()" factory method, and make it
     * return "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initSsoServerSessSvc(MBeanServer server) 
        throws Exception {
        final String oid =
            getGroupOid(
                "SsoServerSessSvc", "1.3.6.1.4.1.42.2.230.3.1.1.2.1.11");
        ObjectName objname = null;
        if (server != null) {
            objname =
                getGroupObjectName("SsoServerSessSvc",
                    oid, mibName + srvPrfx + "SsoServerSessSvc");
        }
        final SsoServerSessSvcMeta meta =
            createSsoServerSessSvcMetaNode(
                "SsoServerSessSvc",
                oid,
                objname,
                server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the "SsoServerSessSvcMBean"
            // interface.
            //
            sessSvcGroup =
                (SsoServerSessSvcMBean) createSsoServerSessSvcMBean(
                    "SsoServerSessSvc", oid, objname, server);
            meta.setInstance ((SsoServerSessSvcMBean)sessSvcGroup);
            registerGroupNode("SsoServerSessSvc", oid, objname, meta,
                sessSvcGroup, server);
        }
    }


    /**
     * Factory method for "SsoServerSessSvc" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerSessSvc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "SsoServerSessSvc" group (SsoServerSessSvcMeta)
     * 
     **/
    protected SsoServerSessSvcMeta createSsoServerSessSvcMetaNode(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        return new SsoServerSessSvcMeta(this, objectserver);
    }


    /**
     * Factory method for "SsoServerSessSvc" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerSessSvc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "SsoServerSessSvc" group (SsoServerSessSvc)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "SsoServerSessSvcMBean"
     * interface.
     **/
    protected Object createSsoServerSessSvcMBean(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {

        // Note that when using standard metadata,
        // the returned object must implement the "SsoServerSessSvcMBean"
        // interface.
        //
        if (server != null) 
            return new SsoServerSessSvcImpl(this,server);
        else 
            return new SsoServerSessSvcImpl(this);
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "SsoServerAuthSvc" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "SsoServerAuthSvc" group.
     * 
     * To disable support of this group, redefine the 
     * "createSsoServerAuthSvcMetaNode()" factory method, and make it
     * return "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initSsoServerAuthSvc(MBeanServer server) 
        throws Exception {
        final String oid =
            getGroupOid(
                "SsoServerAuthSvc", "1.3.6.1.4.1.42.2.230.3.1.1.2.1.10");
        ObjectName objname = null;
        if (server != null) {
            objname =
                getGroupObjectName("SsoServerAuthSvc",
                    oid, mibName + srvPrfx + "SsoServerAuthSvc");
        }
        final SsoServerAuthSvcMeta meta =
            createSsoServerAuthSvcMetaNode(
                "SsoServerAuthSvc",
                oid,
                objname,
                server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the "SsoServerAuthSvcMBean"
            // interface.
            //
            authSvcGroup =
                (SsoServerAuthSvcMBean) createSsoServerAuthSvcMBean(
                    "SsoServerAuthSvc", oid, objname, server);
            meta.setInstance ((SsoServerAuthSvcMBean)authSvcGroup);
            registerGroupNode("SsoServerAuthSvc", oid, objname, meta,
                authSvcGroup, server);
        }
    }


    /**
     * Factory method for "SsoServerAuthSvc" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerAuthSvc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "SsoServerAuthSvc" group (SsoServerAuthSvcMeta)
     * 
     **/
    protected SsoServerAuthSvcMeta createSsoServerAuthSvcMetaNode(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        return new SsoServerAuthSvcMeta(this, objectserver);
    }


    /**
     * Factory method for "SsoServerAuthSvc" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerAuthSvc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "SsoServerAuthSvc" group (SsoServerAuthSvc)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "SsoServerAuthSvcMBean"
     * interface.
     **/
    protected Object createSsoServerAuthSvcMBean(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {

        // Note that when using standard metadata,
        // the returned object must implement the "SsoServerAuthSvcMBean"
        // interface.
        //
        if (server != null) 
            return new SsoServerAuthSvcImpl(this,server);
        else 
            return new SsoServerAuthSvcImpl(this);
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "SsoServerTopology" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "SsoServerTopology" group.
     * 
     * To disable support of this group, redefine the 
     * "createSsoServerTopologyMetaNode()" factory method, and make it
     * return "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initSsoServerTopology(MBeanServer server) 
        throws Exception {
        final String oid =
            getGroupOid(
                "SsoServerTopology", "1.3.6.1.4.1.42.2.230.3.1.1.2.1.8");
        ObjectName objname = null;
        if (server != null) {
            objname =
                getGroupObjectName("SsoServerTopology",
                    oid, mibName + srvPrfx + "SsoServerTopology");
        }
        final SsoServerTopologyMeta meta =
            createSsoServerTopologyMetaNode(
                "SsoServerTopology", oid, objname, server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the "SsoServerTopologyMBean"
            // interface.
            //
            topologyGroup =
                (SsoServerTopologyMBean) createSsoServerTopologyMBean(
                    "SsoServerTopology", oid, objname, server);
            meta.setInstance ((SsoServerTopologyMBean)topologyGroup);
            registerGroupNode("SsoServerTopology", oid, objname, meta,
                topologyGroup, server);
        }
    }


    /**
     * Factory method for "SsoServerTopology" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerTopology")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "SsoServerTopology" group (SsoServerTopologyMeta)
     * 
     **/
    protected SsoServerTopologyMeta createSsoServerTopologyMetaNode(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        return new SsoServerTopologyMeta(this, objectserver);
    }


    /**
     * Factory method for "SsoServerTopology" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerTopology")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "SsoServerTopology" group (SsoServerTopology)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "SsoServerTopologyMBean"
     * interface.
     **/
    protected Object createSsoServerTopologyMBean(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {

        // Note that when using standard metadata,
        // the returned object must implement the "SsoServerTopologyMBean"
        // interface.
        //
        if (server != null) 
            return new SsoServerTopologyImpl(this,server);
        else 
            return new SsoServerTopologyImpl(this);
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "SsoServerEntitlementSvc" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "SsoServerEntitlementSvc" group.
     * 
     * To disable support of this group, redefine the 
     * "createSsoServerEntitlementSvcMetaNode()" factory method, and make it
     * return "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initSsoServerEntitlementSvc(MBeanServer server) 
        throws Exception {
        final String oid = getGroupOid(
            "SsoServerEntitlementSvc", "1.3.6.1.4.1.42.2.230.3.1.1.2.1.23");
        ObjectName objname = null;
        if (server != null) {
            objname = getGroupObjectName("SsoServerEntitlementSvc",
                oid, mibName + srvPrfx + "SsoServerEntitlementSvc");
        }
        final SsoServerEntitlementSvcMeta meta =
            createSsoServerEntitlementSvcMetaNode(
                "SsoServerEntitlementSvc", oid, objname, server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the
            // "SsoServerEntitlementSvcMBean" interface.
            //
            entitlementsGroup =
                (SsoServerEntitlementSvcMBean)
                    createSsoServerEntitlementSvcMBean(
                        "SsoServerEntitlementSvc", oid, objname, server);
            meta.setInstance((SsoServerEntitlementSvcMBean)entitlementsGroup);
            registerGroupNode("SsoServerEntitlementSvc", oid, objname, meta,
                entitlementsGroup, server);
        }
    }


    /**
     * Factory method for "SsoServerEntitlementSvc" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerEntitlementSvc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "SsoServerEntitlementSvc" group (SsoServerEntitlementSvcMeta)
     * 
     **/
    protected SsoServerEntitlementSvcMeta createSsoServerEntitlementSvcMetaNode(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        return new SsoServerEntitlementSvcMeta(this, objectserver);
    }


    /**
     * Factory method for "SsoServerEntitlementSvc" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerEntitlementSvc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "SsoServerEntitlementSvc" group (SsoServerEntitlementSvc)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "SsoServerEntitlementSvcMBean"
     * interface.
     **/
    protected Object createSsoServerEntitlementSvcMBean(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {

        // Note that when using standard metadata,
        // the returned object must implement the "SsoServerEntitlementSvcMBean"
        // interface.
        //
        if (server != null) 
            return new SsoServerEntitlementSvcImpl(this,server);
        else 
            return new SsoServerEntitlementSvcImpl(this);
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "SsoServerWSSAgents" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "SsoServerWSSAgents" group.
     * 
     * To disable support of this group, redefine the 
     * "createSsoServerWSSAgentsMetaNode()" factory method, and make it
     * return "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initSsoServerWSSAgents(MBeanServer server) 
        throws Exception {
        final String oid =
            getGroupOid(
                "SsoServerWSSAgents", "1.3.6.1.4.1.42.2.230.3.1.1.2.1.22");
        ObjectName objname = null;
        if (server != null) {
            objname =
                getGroupObjectName("SsoServerWSSAgents",
                    oid, mibName + srvPrfx + "SsoServerWSSAgents");
        }
        final SsoServerWSSAgentsMeta meta =
            createSsoServerWSSAgentsMetaNode(
                "SsoServerWSSAgents", oid, objname, server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the "SsoServerWSSAgentsMBean"
            // interface.
            //
            wssAgentsGroup = (SsoServerWSSAgentsMBean) createSsoServerWSSAgentsMBean("SsoServerWSSAgents", oid, objname, server);
            meta.setInstance ((SsoServerWSSAgentsMBean)wssAgentsGroup);
            registerGroupNode("SsoServerWSSAgents", oid, objname, meta,
                wssAgentsGroup, server);
        }
    }


    /**
     * Factory method for "SsoServerWSSAgents" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerWSSAgents")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "SsoServerWSSAgents" group (SsoServerWSSAgentsMeta)
     * 
     **/
    protected SsoServerWSSAgentsMeta createSsoServerWSSAgentsMetaNode(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        return new SsoServerWSSAgentsMeta(this, objectserver);
    }


    /**
     * Factory method for "SsoServerWSSAgents" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerWSSAgents")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "SsoServerWSSAgents" group (SsoServerWSSAgents)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "SsoServerWSSAgentsMBean"
     * interface.
     **/
    protected Object createSsoServerWSSAgentsMBean(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {

        // Note that when using standard metadata,
        // the returned object must implement the "SsoServerWSSAgentsMBean"
        // interface.
        //
        if (server != null) 
            return new SsoServerWSSAgentsImpl(this,server);
        else 
            return new SsoServerWSSAgentsImpl(this);
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "SsoServerPolicyAgents" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "SsoServerPolicyAgents" group.
     * 
     * To disable support of this group, redefine the 
     * "createSsoServerPolicyAgentsMetaNode()" factory method, and make it
     * return "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initSsoServerPolicyAgents(MBeanServer server) 
        throws Exception {
        final String oid =
            getGroupOid(
                "SsoServerPolicyAgents", "1.3.6.1.4.1.42.2.230.3.1.1.2.1.21");
        ObjectName objname = null;
        if (server != null) {
            objname =
                getGroupObjectName("SsoServerPolicyAgents",
                    oid, mibName + srvPrfx + "SsoServerPolicyAgents");
        }
        final SsoServerPolicyAgentsMeta meta =
            createSsoServerPolicyAgentsMetaNode(
                "SsoServerPolicyAgents", oid, objname, server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the
            // "SsoServerPolicyAgentsMBean" interface.
            //
            policyAgentsGroup =
                (SsoServerPolicyAgentsMBean) createSsoServerPolicyAgentsMBean(
                    "SsoServerPolicyAgents", oid, objname, server);
            meta.setInstance ((SsoServerPolicyAgentsMBean)policyAgentsGroup);
            registerGroupNode("SsoServerPolicyAgents", oid, objname, meta,
                policyAgentsGroup, server);
        }
    }


    /**
     * Factory method for "SsoServerPolicyAgents" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerPolicyAgents")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "SsoServerPolicyAgents" group (SsoServerPolicyAgentsMeta)
     * 
     **/
    protected SsoServerPolicyAgentsMeta createSsoServerPolicyAgentsMetaNode(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        return new SsoServerPolicyAgentsMeta(this, objectserver);
    }


    /**
     * Factory method for "SsoServerPolicyAgents" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerPolicyAgents")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "SsoServerPolicyAgents" group (SsoServerPolicyAgents)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "SsoServerPolicyAgentsMBean"
     * interface.
     **/
    protected Object createSsoServerPolicyAgentsMBean(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {

        // Note that when using standard metadata,
        // the returned object must implement the "SsoServerPolicyAgentsMBean"
        // interface.
        //
        if (server != null) 
            return new SsoServerPolicyAgentsImpl(this,server);
        else 
            return new SsoServerPolicyAgentsImpl(this);
    }


    // ------------------------------------------------------------
    // 
    // Initialization of the "SsoServerIDFFSvc" group.
    // 
    // ------------------------------------------------------------


    /**
     * Initialization of the "SsoServerIDFFSvc" group.
     * 
     * To disable support of this group, redefine the 
     * "createSsoServerIDFFSvcMetaNode()" factory method, and make it
     * return "null"
     * 
     * @param server    MBeanServer for this group (may be null)
     * 
     **/
    protected void initSsoServerIDFFSvc(MBeanServer server) 
        throws Exception {
        final String oid =
            getGroupOid(
                "SsoServerIDFFSvc", "1.3.6.1.4.1.42.2.230.3.1.1.2.1.20");
        ObjectName objname = null;
        if (server != null) {
            objname =
                getGroupObjectName("SsoServerIDFFSvc",
                    oid, mibName + srvPrfx + "SsoServerIDFFSvc");
        }
        final SsoServerIDFFSvcMeta meta =
            createSsoServerIDFFSvcMetaNode(
                "SsoServerIDFFSvc", oid, objname, server);
        if (meta != null) {
            meta.registerTableNodes( this, server );

            // Note that when using standard metadata,
            // the returned object must implement the "SsoServerIDFFSvcMBean"
            // interface.
            //
            idffSvcGroup = (SsoServerIDFFSvcMBean)createSsoServerIDFFSvcMBean(
                "SsoServerIDFFSvc", oid, objname, server);
            meta.setInstance ((SsoServerIDFFSvcMBean)idffSvcGroup);
            registerGroupNode("SsoServerIDFFSvc", oid, objname, meta,
                idffSvcGroup, server);
        }
    }


    /**
     * Factory method for "SsoServerIDFFSvc" group metadata class.
     * 
     * You can redefine this method if you need to replace the default
     * generated metadata class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerIDFFSvc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the metadata class generated for the
     *         "SsoServerIDFFSvc" group (SsoServerIDFFSvcMeta)
     * 
     **/
    protected SsoServerIDFFSvcMeta createSsoServerIDFFSvcMetaNode(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {
        return new SsoServerIDFFSvcMeta(this, objectserver);
    }


    /**
     * Factory method for "SsoServerIDFFSvc" group MBean.
     * 
     * You can redefine this method if you need to replace the default
     * generated MBean class with your own customized class.
     * 
     * @param groupName Name of the group ("SsoServerIDFFSvc")
     * @param groupOid  OID of this group
     * @param groupObjname ObjectName for this group (may be null)
     * @param server    MBeanServer for this group (may be null)
     * 
     * @return An instance of the MBean class generated for the
     *         "SsoServerIDFFSvc" group (SsoServerIDFFSvc)
     * 
     * Note that when using standard metadata,
     * the returned object must implement the "SsoServerIDFFSvcMBean"
     * interface.
     **/
    protected Object createSsoServerIDFFSvcMBean(
        String groupName,
        String groupOid,
        ObjectName groupObjname,
        MBeanServer server)
    {

        // Note that when using standard metadata,
        // the returned object must implement the "SsoServerIDFFSvcMBean"
        // interface.
        //
        if (server != null) 
            return new SsoServerIDFFSvcImpl(this,server);
        else 
            return new SsoServerIDFFSvcImpl(this);
    }



    // ------------------------------------------------------------
    // 
    // Implements the "registerTableMeta" method defined in "SnmpMib".
    // See the "SnmpMib" Javadoc API for more details.
    // 
    // ------------------------------------------------------------

    public void registerTableMeta( String name, SnmpMibTable meta) {
        if (metadatas == null) return;
        if (name == null) return;
        metadatas.put(name,meta);
    }


    // ------------------------------------------------------------
    // 
    // Implements the "getRegisteredTableMeta" method defined in "SnmpMib".
    // See the "SnmpMib" Javadoc API for more details.
    // 
    // ------------------------------------------------------------

    public SnmpMibTable getRegisteredTableMeta( String name ) {
        if (metadatas == null) return null;
        if (name == null) return null;
        return (SnmpMibTable) metadatas.get(name);
    }

    public SnmpStandardObjectServer getStandardObjectServer() {
        if (objectserver == null) 
            objectserver = new SnmpStandardObjectServer();
        return objectserver;
    }

    protected Object getAuthSvcGroup() {
        return authSvcGroup;
    }

    protected Object getSessSvcGroup() {
        return sessSvcGroup;
    }

    protected Object getLoggingSvcGroup() {
        return loggingSvcGroup;
    }

    protected Object getPolicySvcGroup() {
        return policySvcGroup;
    }

    protected Object getIdrepoSvcGroup() {
        return idrepoSvcGroup;
    }

    protected Object getSmSvcGroup() {
        return svcmgmtSvcGroup;
    }

    protected Object getSaml1SvcGroup() {
        return saml1SvcGroup;
    }

    protected Object getSaml2SvcGroup() {
        return saml2SvcGroup;
    }

    protected Object getIdffSvcGroup() {
        return idffSvcGroup;
    }

    protected Object getTopologyGroup() {
        return topologyGroup;
    }

    protected Object getSvrInstanceGroup() {
        return instanceGroup;
    }

    protected Object getWssAgentsGroup() {
        return wssAgentsGroup;
    }

    protected Object getFedCotsGroup() {
        return fedCotsGroup;
    }

    protected Object getPolicyAgentsGroup() {
        return policyAgentsGroup;
    }

    protected Object getFedEntitiesGroup() {
        return fedEntitiesGroup;
    }

    protected Object getEntitlementsGroup() {
        return entitlementsGroup;
    }

    private boolean isInitialized = false;

    protected SnmpStandardObjectServer objectserver;

    protected final Hashtable metadatas = new Hashtable();
}
